import type { SketchName, Topic } from "./types";

export const CAPTIONS: Record<SketchName, string> = {
  push: "Figure — A push sends the object away from the hand.",
  pull: "Figure — A pull brings the object toward you.",
  shadow: "Figure — An opaque object blocks light and leaves a shadow.",
  motion: "Figure — Distance is the path. Displacement is the straight change from start to finish.",
  circuit: "Figure — A closed circuit: cell, switch, and bulb.",
  magnet: "Figure — Field lines leave the north pole and enter the south pole outside the magnet.",
  mirror: "Figure — A concave mirror. Rays parallel to the axis pass through the principal focus after reflection.",
  wave: "Figure — A transverse wave. Crest to crest is one wavelength.",
  pendulum: "Figure — A simple pendulum. The length is measured to the centre of the bob.",
  heat: "Figure — Heat flows from the hotter end toward the colder end.",
  gravity: "Figure — Weight acts toward the centre of the Earth.",
  float: "Figure — Upthrust acts upward. Weight acts downward.",
  lever: "Figure — A lever turns about the fulcrum. Effort and load act on opposite sides here.",
  slope: "Figure — An inclined plane lets you raise a load along a longer, gentler path.",
  reflection: "Figure — The angle of incidence equals the angle of reflection. Both are measured from the normal.",
  refraction: "Figure — A ray bends toward the normal when it enters a slower medium such as glass from air.",
  lens: "Figure — A convex lens brings parallel rays together at the principal focus.",
  eye: "Figure — The eye lens forms an image on the retina.",
  prism: "Figure — A glass prism bends violet light more than red light.",
  pressure: "Figure — The same force on a smaller area makes a larger pressure.",
  friction: "Figure — Kinetic friction opposes the sliding.",
  sound: "Figure — A vibrating source sends a sound wave through the air.",
  echo: "Figure — An echo is the reflection of sound. The sound travels to the wall and back.",
  projectile: "Figure — With air resistance ignored, the horizontal velocity stays constant and the vertical motion accelerates downward.",
  circular: "Figure — Centripetal force points toward the centre of the circle.",
  satellite: "Figure — A satellite stays in orbit because its sideways speed keeps matching the curve of the Earth.",
  spring: "Figure — Hooke’s law, F = kx, holds while the spring stays inside its elastic limit.",
  capacitor: "Figure — A parallel-plate capacitor stores opposite charges on the two plates.",
  field: "Figure — Electric field lines leave a positive charge and enter a negative charge.",
  transformer: "Figure — A transformer changes an alternating voltage. It does not work on steady direct current.",
  atom: "Figure — In the Bohr model of hydrogen, the electron occupies definite energy levels.",
  nucleus: "Figure — After one half-life, half of the undecayed nuclei remain.",
  diode: "Figure — A p-n diode conducts much more easily in forward bias than in reverse bias.",
  solar: "Figure — The planets orbit the Sun. The drawing is not to scale.",
  daynight: "Figure — The Sun lights one half of the Earth. The other half is night.",
  measure: "Figure — A measurement needs a number and a unit.",
  graph: "Figure — On a distance–time graph, a steeper straight line means a higher constant speed.",
  storm: "Figure — Air moves from higher pressure toward lower pressure.",
  charge: "Figure — Like charges repel. Unlike charges attract.",
  fuse: "Figure — A fuse is placed in the live wire and melts if the current is too large.",
  rainbow: "Figure — Water droplets disperse sunlight. Red is on the outside of the primary bow.",
  pulley: "Figure — A fixed pulley changes the direction of the pull. It does not reduce the load by itself.",
  gas: "Figure — In the kinetic picture, gas pressure comes from molecules hitting the walls.",
  solid: "Figure — Stress is force per area. Strain is the change in length divided by the original length.",
  emwave: "Figure — In an electromagnetic wave the electric and magnetic fields are perpendicular to each other and to the direction of travel.",
  slits: "Figure — Two slits give a pattern of bright and dark fringes on the screen.",
  photo: "Figure — A photon ejects an electron only if its energy is at least the work function.",
  vector: "Figure — Vectors add tip to tail. The resultant depends on direction, not only on size.",
  freefall: "Figure — In free fall near the Earth, the acceleration is g downward if air resistance is ignored.",
  work: "Figure — Work is done when a force moves its point of application.",
  collision: "Figure — In a collision the forces between the two bodies are an action–reaction pair.",
  ac: "Figure — An alternating voltage changes direction. The household value is an RMS value.",
};

const RULES: [RegExp, SketchName][] = [
  [/echo/, "echo"],
  [/pendulum|oscillat/, "pendulum"],
  [/spring/, "spring"],
  [/fringe|slit|young/, "slits"],
  [/photon|photoelectric|de broglie|matter wave/, "photo"],
  [/nucleus|nuclei|half-life|half life|radioact/, "nucleus"],
  [/bohr|atom|hydrogen level/, "atom"],
  [/diode|semiconductor|logic gate/, "diode"],
  [/transformer|faraday|induction/, "transformer"],
  [/alternating|rms|household supply/, "ac"],
  [/capacitor|capacitance/, "capacitor"],
  [/coulomb|electric field|gauss|charge/, "field"],
  [/lightning/, "charge"],
  [/fuse|household|domestic|live wire/, "fuse"],
  [/magnetic force|lorentz|centripet|circular/, "circular"],
  [/magnet/, "magnet"],
  [/eye|myopia|hypermetropia|retina/, "eye"],
  [/prism|dispers|rainbow|scatter|colourful|colorful/, "prism"],
  [/lens|refraction/, "lens"],
  [/mirror|reflect|shiny|dull/, "mirror"],
  [/pressure|pascal|thrust/, "pressure"],
  [/friction|rough|smooth/, "friction"],
  [/float|sink|buoy|archimed|upthrust|density/, "float"],
  [/pulley|wheel|axle/, "pulley"],
  [/lever|seesaw/, "lever"],
  [/slope|incline/, "slope"],
  [/shadow|opaque|blocks light|see with light|light and dark|light travels/, "shadow"],
  [/wave|beat|wavelength/, "wave"],
  [/sound|loud|soft|vibrat/, "sound"],
  [/heat|temperature|thermal|thermo|specific|hot|cold|warm|cool/, "heat"],
  [/graph|equation/, "graph"],
  [/free fall|freefall/, "freefall"],
  [/satellite|orbit|solar|planet/, "solar"],
  [/weight|gravitat|gravity|earth pull/, "gravity"],
  [/work|power|energy|joule/, "work"],
  [/momentum|collision|newton/, "collision"],
  [/projectile|vector/, "vector"],
  [/storm|cyclone|wind|air pressure/, "storm"],
  [/day|night|turning earth/, "daynight"],
  [/measure|unit|significant|ruler|length/, "measure"],
  [/speed|velocity|accel|motion|displacement|moving|still|starting|stopping|path/, "motion"],
  [/pull/, "pull"],
  [/push|force/, "push"],
];

export function figureFor(topic: Pick<Topic, "title" | "sketch" | "sketchCaption">): {
  name: SketchName;
  caption: string;
} {
  const title = topic.title.toLowerCase();
  const inferred = RULES.find(([pattern]) => pattern.test(title))?.[1] ?? "motion";
  const name = topic.sketch ?? inferred;
  return { name, caption: topic.sketchCaption ?? CAPTIONS[name] };
}
