import type { Formula } from "./types";

export const formulas: Formula[] = [
  {
    id: "speed",
    name: "Speed",
    latex: "v = \\dfrac{s}{t}",
    plain: "speed = distance / time",
    meaning: "How fast distance is covered. School speed is distance divided by time, with no direction.",
    variables: [
      { symbol: "v", meaning: "speed", unit: "m/s" },
      { symbol: "s", meaning: "distance", unit: "m" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "velocity",
    name: "Average velocity",
    latex: "v_{\\mathrm{av}} = \\dfrac{\\text{displacement}}{\\text{time}}",
    plain: "average velocity = displacement / time",
    meaning:
      "Average velocity uses displacement, not the path length, and it has a direction. Its magnitude is not always the average speed.",
    variables: [
      { symbol: "v_av", meaning: "average velocity", unit: "m/s" },
      { symbol: "s", meaning: "displacement", unit: "m" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "acceleration",
    name: "Acceleration",
    latex: "a = \\dfrac{v - u}{t}",
    plain: "a = (v − u) / t",
    meaning:
      "Acceleration is the change in velocity divided by the time taken. Slowing down is acceleration opposite to the velocity.",
    variables: [
      { symbol: "a", meaning: "acceleration", unit: "m/s²" },
      { symbol: "v", meaning: "final velocity", unit: "m/s" },
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "average-speed",
    name: "Average speed",
    latex: "v_{\\mathrm{av}} = \\dfrac{\\text{total distance}}{\\text{total time}}",
    plain: "average speed = total distance / total time",
    meaning: "Use total distance and total time for the whole journey, not a plain average of the two speeds unless the times are equal.",
    variables: [
      { symbol: "v_av", meaning: "average speed", unit: "m/s" },
    ],
  },
  {
    id: "v-uat",
    name: "First equation of motion",
    latex: "v = u + at",
    plain: "v = u + at",
    meaning: "Final velocity when acceleration is constant.",
    variables: [
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "v", meaning: "final velocity", unit: "m/s" },
      { symbol: "a", meaning: "acceleration", unit: "m/s²" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "s-uat",
    name: "Second equation of motion",
    latex: "s = ut + \\tfrac{1}{2}at^{2}",
    plain: "s = ut + (1/2)at²",
    meaning: "Displacement when acceleration is constant.",
    variables: [
      { symbol: "s", meaning: "displacement", unit: "m" },
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "a", meaning: "acceleration", unit: "m/s²" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "v2-uas",
    name: "Third equation of motion",
    latex: "v^{2} = u^{2} + 2as",
    plain: "v² = u² + 2as",
    meaning: "Links velocity and displacement when acceleration is constant and time is not known. The checker reports the non-negative square root.",
    variables: [
      { symbol: "u", meaning: "initial velocity", unit: "m/s" },
      { symbol: "v", meaning: "final speed", unit: "m/s" },
      { symbol: "a", meaning: "acceleration", unit: "m/s²" },
      { symbol: "s", meaning: "displacement", unit: "m" },
    ],
  },
  {
    id: "newton-second",
    name: "Newton’s second law",
    latex: "F = ma",
    plain: "F = ma",
    meaning: "Net force equals mass times acceleration. Force and acceleration are in the same direction.",
    variables: [
      { symbol: "F", meaning: "net force", unit: "N" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "a", meaning: "acceleration", unit: "m/s²" },
    ],
  },
  {
    id: "momentum",
    name: "Momentum",
    latex: "p = mv",
    plain: "p = mv",
    meaning: "Momentum is mass times velocity. It is a vector; this school form uses the signed velocity along a line.",
    variables: [
      { symbol: "p", meaning: "momentum", unit: "kg m/s" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "v", meaning: "velocity", unit: "m/s" },
    ],
  },
  {
    id: "impulse",
    name: "Impulse",
    latex: "F\\Delta t = \\Delta p",
    plain: "force × time = change in momentum",
    meaning: "A force acting for a short time changes momentum.",
    variables: [
      { symbol: "F", meaning: "average force", unit: "N" },
      { symbol: "Δt", meaning: "time interval", unit: "s" },
      { symbol: "Δp", meaning: "change in momentum", unit: "kg m/s" },
    ],
  },
  {
    id: "weight",
    name: "Weight",
    latex: "W = mg",
    plain: "W = mg",
    meaning: "Weight is the gravitational force on a mass. Use g = 9.8 m/s² unless the question says to use 10.",
    variables: [
      { symbol: "W", meaning: "weight", unit: "N" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
    ],
  },
  {
    id: "gravitation",
    name: "Newton’s law of gravitation",
    latex: "F = G\\dfrac{m_1 m_2}{r^{2}}",
    plain: "F = G m1 m2 / r²",
    meaning: "Every pair of masses attracts. G is 6.67 × 10⁻¹¹ N m²/kg². r is the centre-to-centre distance.",
    variables: [
      { symbol: "F", meaning: "gravitational force", unit: "N" },
      { symbol: "G", meaning: "gravitational constant", unit: "N m²/kg²" },
      { symbol: "m_1, m_2", meaning: "masses", unit: "kg" },
      { symbol: "r", meaning: "separation of centres", unit: "m" },
    ],
  },
  {
    id: "g-surface",
    name: "Gravity at a surface",
    latex: "g = \\dfrac{GM}{R^{2}}",
    plain: "g = GM / R²",
    meaning: "Gravitational acceleration at the surface of a spherical body.",
    variables: [
      { symbol: "g", meaning: "surface gravity", unit: "m/s²" },
      { symbol: "M", meaning: "mass of the body", unit: "kg" },
      { symbol: "R", meaning: "radius", unit: "m" },
    ],
  },
  {
    id: "orbital-speed",
    name: "Orbital speed",
    latex: "v = \\sqrt{\\dfrac{GM}{r}}",
    plain: "v = sqrt(GM / r)",
    meaning: "Speed of a satellite in a circular orbit of radius r, measured from the centre of the planet.",
    variables: [
      { symbol: "v", meaning: "orbital speed", unit: "m/s" },
      { symbol: "M", meaning: "planet mass", unit: "kg" },
      { symbol: "r", meaning: "orbit radius", unit: "m" },
    ],
  },
  {
    id: "escape-speed",
    name: "Escape speed",
    latex: "v_{e} = \\sqrt{\\dfrac{2GM}{R}}",
    plain: "escape speed = sqrt(2GM / R)",
    meaning: "The least launch speed, ignoring air, that lets an object leave a body’s surface and not fall back.",
    variables: [
      { symbol: "v_e", meaning: "escape speed", unit: "m/s" },
      { symbol: "M", meaning: "planet mass", unit: "kg" },
      { symbol: "R", meaning: "planet radius", unit: "m" },
    ],
  },
  {
    id: "work",
    name: "Work",
    latex: "W = Fs\\cos\\theta",
    plain: "W = Fs cos θ",
    meaning: "Work is force times displacement in the direction of the force. θ is the angle between them. Work is a scalar and can be negative.",
    variables: [
      { symbol: "W", meaning: "work", unit: "J" },
      { symbol: "F", meaning: "force", unit: "N" },
      { symbol: "s", meaning: "displacement", unit: "m" },
      { symbol: "θ", meaning: "angle between F and s", unit: "degree" },
    ],
  },
  {
    id: "kinetic-energy",
    name: "Kinetic energy",
    latex: "K = \\tfrac{1}{2}mv^{2}",
    plain: "K = (1/2)mv²",
    meaning: "Energy due to motion. It is never negative.",
    variables: [
      { symbol: "K", meaning: "kinetic energy", unit: "J" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "v", meaning: "speed", unit: "m/s" },
    ],
  },
  {
    id: "potential-energy",
    name: "Gravitational potential energy",
    latex: "U = mgh",
    plain: "U = mgh",
    meaning: "Near Earth, the change in gravitational potential energy is mgh when height is measured upward from a chosen zero.",
    variables: [
      { symbol: "U", meaning: "potential energy", unit: "J" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
      { symbol: "h", meaning: "height", unit: "m" },
    ],
  },
  {
    id: "power",
    name: "Power",
    latex: "P = \\dfrac{W}{t}",
    plain: "P = W / t",
    meaning: "Power is the rate of doing work.",
    variables: [
      { symbol: "P", meaning: "power", unit: "W" },
      { symbol: "W", meaning: "work", unit: "J" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "pressure",
    name: "Pressure",
    latex: "P = \\dfrac{F}{A}",
    plain: "pressure = force / area",
    meaning: "Pressure is force perpendicular to a surface, divided by the area of that surface.",
    variables: [
      { symbol: "P", meaning: "pressure", unit: "Pa" },
      { symbol: "F", meaning: "perpendicular force", unit: "N" },
      { symbol: "A", meaning: "area", unit: "m²" },
    ],
  },
  {
    id: "liquid-pressure",
    name: "Pressure in a liquid",
    latex: "P = h\\rho g",
    plain: "P = hρg",
    meaning: "Gauge pressure at depth h in a still liquid of density ρ.",
    variables: [
      { symbol: "h", meaning: "depth", unit: "m" },
      { symbol: "ρ", meaning: "density", unit: "kg/m³" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
    ],
  },
  {
    id: "density",
    name: "Density",
    latex: "\\rho = \\dfrac{m}{V}",
    plain: "density = mass / volume",
    meaning: "Mass packed into a given volume. An object floats in a liquid if its average density is less than the liquid’s density.",
    variables: [
      { symbol: "ρ", meaning: "density", unit: "kg/m³" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "V", meaning: "volume", unit: "m³" },
    ],
  },
  {
    id: "wave-speed",
    name: "Wave speed",
    latex: "v = f\\lambda",
    plain: "v = fλ",
    meaning: "Wave speed equals frequency times wavelength.",
    variables: [
      { symbol: "v", meaning: "wave speed", unit: "m/s" },
      { symbol: "f", meaning: "frequency", unit: "Hz" },
      { symbol: "λ", meaning: "wavelength", unit: "m" },
    ],
  },
  {
    id: "echo-distance",
    name: "Echo distance",
    latex: "d = \\dfrac{vt}{2}",
    plain: "d = vt / 2",
    meaning: "The sound goes to the wall and back, so the one-way distance is half of speed times the echo time.",
    variables: [
      { symbol: "d", meaning: "distance to the reflector", unit: "m" },
      { symbol: "v", meaning: "speed of sound", unit: "m/s" },
      { symbol: "t", meaning: "time until the echo", unit: "s" },
    ],
  },
  {
    id: "mirror-formula",
    name: "Mirror formula",
    latex: "\\dfrac{1}{v} + \\dfrac{1}{u} = \\dfrac{1}{f}",
    plain: "1/v + 1/u = 1/f",
    meaning: "New Cartesian sign convention: light travels left to right toward the mirror. Object distance u is negative. A concave mirror has negative f. A real image has negative v.",
    variables: [
      { symbol: "u", meaning: "object distance", unit: "m or cm" },
      { symbol: "v", meaning: "image distance", unit: "same as u" },
      { symbol: "f", meaning: "focal length", unit: "same as u" },
    ],
  },
  {
    id: "lens-formula",
    name: "Lens formula",
    latex: "\\dfrac{1}{v} - \\dfrac{1}{u} = \\dfrac{1}{f}",
    plain: "1/v − 1/u = 1/f",
    meaning: "New Cartesian sign convention. Object distance u is negative. A convex lens has positive f. A real image has positive v.",
    variables: [
      { symbol: "u", meaning: "object distance", unit: "m or cm" },
      { symbol: "v", meaning: "image distance", unit: "same as u" },
      { symbol: "f", meaning: "focal length", unit: "same as u" },
    ],
  },
  {
    id: "mirror-magnification",
    name: "Mirror magnification",
    latex: "m = \\dfrac{h'}{h} = -\\dfrac{v}{u}",
    plain: "m = h'/h = −v/u",
    meaning: "Negative magnification means the image is inverted.",
    variables: [
      { symbol: "m", meaning: "magnification", unit: "no unit" },
      { symbol: "h'", meaning: "image height", unit: "m" },
      { symbol: "h", meaning: "object height", unit: "m" },
    ],
  },
  {
    id: "lens-magnification",
    name: "Lens magnification",
    latex: "m = \\dfrac{h'}{h} = \\dfrac{v}{u}",
    plain: "m = h'/h = v/u",
    meaning: "For a lens, magnification is v/u with the sign convention. A negative value means an inverted image.",
    variables: [
      { symbol: "m", meaning: "magnification", unit: "no unit" },
    ],
  },
  {
    id: "lens-power",
    name: "Power of a lens",
    latex: "P = \\dfrac{1}{f}",
    plain: "P = 1/f with f in metres",
    meaning: "Power is in dioptres when focal length is in metres. A convex lens has positive power.",
    variables: [
      { symbol: "P", meaning: "power", unit: "D" },
      { symbol: "f", meaning: "focal length", unit: "m" },
    ],
  },
  {
    id: "refractive-index",
    name: "Refractive index",
    latex: "n = \\dfrac{c}{v} = \\dfrac{\\sin i}{\\sin r}",
    plain: "n = c/v = sin i / sin r",
    meaning: "For light entering a denser medium, Snell’s law uses the absolute refractive index when the first medium is air. Angles are measured from the normal.",
    variables: [
      { symbol: "n", meaning: "refractive index", unit: "no unit" },
      { symbol: "c", meaning: "speed of light in vacuum", unit: "m/s" },
      { symbol: "v", meaning: "speed of light in the medium", unit: "m/s" },
      { symbol: "i", meaning: "angle of incidence", unit: "degree" },
      { symbol: "r", meaning: "angle of refraction", unit: "degree" },
    ],
  },
  {
    id: "ohms-law",
    name: "Ohm’s law",
    latex: "V = IR",
    plain: "V = IR",
    meaning: "For a given conductor at constant temperature, potential difference is proportional to current.",
    variables: [
      { symbol: "V", meaning: "potential difference", unit: "V" },
      { symbol: "I", meaning: "current", unit: "A" },
      { symbol: "R", meaning: "resistance", unit: "Ω" },
    ],
  },
  {
    id: "series-resistance",
    name: "Resistors in series",
    latex: "R = R_1 + R_2 + R_3 + \\cdots",
    plain: "R = R1 + R2 + R3 + …",
    meaning: "The same current flows through each resistor. Resistances add.",
    variables: [{ symbol: "R", meaning: "equivalent resistance", unit: "Ω" }],
  },
  {
    id: "parallel-resistance",
    name: "Resistors in parallel",
    latex: "\\dfrac{1}{R} = \\dfrac{1}{R_1} + \\dfrac{1}{R_2} + \\cdots",
    plain: "1/R = 1/R1 + 1/R2 + …",
    meaning: "Each branch has the same potential difference. The equivalent resistance is smaller than the smallest branch.",
    variables: [{ symbol: "R", meaning: "equivalent resistance", unit: "Ω" }],
  },
  {
    id: "electric-power",
    name: "Electric power",
    latex: "P = VI = I^{2}R = \\dfrac{V^{2}}{R}",
    plain: "P = VI = I²R = V²/R",
    meaning: "These forms match only when V = IR for that resistor.",
    variables: [
      { symbol: "P", meaning: "power", unit: "W" },
      { symbol: "V", meaning: "potential difference", unit: "V" },
      { symbol: "I", meaning: "current", unit: "A" },
      { symbol: "R", meaning: "resistance", unit: "Ω" },
    ],
  },
  {
    id: "joule-heat",
    name: "Joule heating",
    latex: "H = I^{2}Rt",
    plain: "H = I²Rt",
    meaning: "Heat produced in a resistor. H is in joules when I is in amperes, R in ohms, and t in seconds.",
    variables: [
      { symbol: "H", meaning: "heat", unit: "J" },
      { symbol: "I", meaning: "current", unit: "A" },
      { symbol: "R", meaning: "resistance", unit: "Ω" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "friction",
    name: "Kinetic friction",
    latex: "f_{k} = \\mu_{k} N",
    plain: "friction = μN",
    meaning: "Kinetic friction opposes sliding. N is the normal force. Static friction can be smaller than μₛN; μₛN is the maximum.",
    variables: [
      { symbol: "f", meaning: "friction", unit: "N" },
      { symbol: "μ", meaning: "coefficient of friction", unit: "no unit" },
      { symbol: "N", meaning: "normal force", unit: "N" },
    ],
  },
  {
    id: "centripetal",
    name: "Centripetal acceleration",
    latex: "a = \\dfrac{v^{2}}{r}",
    plain: "a = v² / r",
    meaning: "A body in uniform circular motion accelerates toward the centre even when its speed is constant.",
    variables: [
      { symbol: "a", meaning: "centripetal acceleration", unit: "m/s²" },
      { symbol: "v", meaning: "speed", unit: "m/s" },
      { symbol: "r", meaning: "radius", unit: "m" },
    ],
  },
  {
    id: "centripetal-force",
    name: "Centripetal force",
    latex: "F = \\dfrac{mv^{2}}{r}",
    plain: "F = mv² / r",
    meaning: "The net inward force required for uniform circular motion. It is not a new kind of force.",
    variables: [
      { symbol: "F", meaning: "net inward force", unit: "N" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "v", meaning: "speed", unit: "m/s" },
      { symbol: "r", meaning: "radius", unit: "m" },
    ],
  },
  {
    id: "torque",
    name: "Torque",
    latex: "\\tau = rF\\sin\\theta",
    plain: "torque = r F sin θ",
    meaning: "The turning effect of a force. θ is the angle between the position vector from the axis and the force.",
    variables: [
      { symbol: "τ", meaning: "torque", unit: "N m" },
      { symbol: "r", meaning: "distance from the axis", unit: "m" },
      { symbol: "F", meaning: "force", unit: "N" },
    ],
  },
  {
    id: "rotation-law",
    name: "Newton’s second law for rotation",
    latex: "\\tau = I\\alpha",
    plain: "τ = Iα",
    meaning: "Net torque equals moment of inertia times angular acceleration, about the same axis.",
    variables: [
      { symbol: "I", meaning: "moment of inertia", unit: "kg m²" },
      { symbol: "α", meaning: "angular acceleration", unit: "rad/s²" },
    ],
  },
  {
    id: "rolling",
    name: "Rolling without slipping",
    latex: "v = r\\omega",
    plain: "v = rω",
    meaning: "For rolling without slipping, the centre-of-mass speed equals radius times angular speed.",
    variables: [
      { symbol: "v", meaning: "centre speed", unit: "m/s" },
      { symbol: "r", meaning: "radius", unit: "m" },
      { symbol: "ω", meaning: "angular speed", unit: "rad/s" },
    ],
  },
  {
    id: "young",
    name: "Young’s modulus",
    latex: "Y = \\dfrac{\\text{stress}}{\\text{strain}} = \\dfrac{F/A}{\\Delta L/L}",
    plain: "Y = stress / strain",
    meaning: "How stiff a solid is under stretching or compression, within the elastic limit.",
    variables: [
      { symbol: "Y", meaning: "Young’s modulus", unit: "Pa" },
      { symbol: "F", meaning: "force", unit: "N" },
      { symbol: "A", meaning: "area", unit: "m²" },
      { symbol: "ΔL", meaning: "change in length", unit: "m" },
      { symbol: "L", meaning: "original length", unit: "m" },
    ],
  },
  {
    id: "bernoulli",
    name: "Bernoulli’s equation",
    latex: "P + \\tfrac{1}{2}\\rho v^{2} + \\rho gh = \\text{constant}",
    plain: "P + ½ρv² + ρgh = constant",
    meaning: "Along a streamline in a steady, non-viscous, incompressible flow.",
    variables: [
      { symbol: "P", meaning: "pressure", unit: "Pa" },
      { symbol: "v", meaning: "flow speed", unit: "m/s" },
      { symbol: "h", meaning: "height", unit: "m" },
    ],
  },
  {
    id: "stokes",
    name: "Stokes’ drag",
    latex: "F = 6\\pi\\eta rv",
    plain: "F = 6πηrv",
    meaning: "Viscous drag on a sphere moving slowly through a fluid.",
    variables: [
      { symbol: "η", meaning: "viscosity", unit: "Pa s" },
      { symbol: "r", meaning: "radius", unit: "m" },
      { symbol: "v", meaning: "speed", unit: "m/s" },
    ],
  },
  {
    id: "heat-capacity",
    name: "Heat and temperature change",
    latex: "Q = mc\\Delta T",
    plain: "Q = mcΔT",
    meaning: "Heat needed to change the temperature of a substance with no change of state. c is specific heat capacity.",
    variables: [
      { symbol: "Q", meaning: "heat", unit: "J" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "c", meaning: "specific heat capacity", unit: "J/kg°C" },
      { symbol: "ΔT", meaning: "temperature change", unit: "°C or K" },
    ],
  },
  {
    id: "linear-expansion",
    name: "Linear expansion",
    latex: "\\Delta L = \\alpha L \\Delta T",
    plain: "ΔL = αLΔT",
    meaning: "Change in length when temperature changes, for a given material.",
    variables: [
      { symbol: "α", meaning: "linear expansivity", unit: "per °C" },
      { symbol: "L", meaning: "original length", unit: "m" },
    ],
  },
  {
    id: "first-law",
    name: "First law of thermodynamics",
    latex: "\\Delta Q = \\Delta U + \\Delta W",
    plain: "ΔQ = ΔU + ΔW",
    meaning: "Heat added to a system goes into internal energy and work done by the system. This is the school sign convention used in NCERT.",
    variables: [
      { symbol: "ΔQ", meaning: "heat added to the system", unit: "J" },
      { symbol: "ΔU", meaning: "change in internal energy", unit: "J" },
      { symbol: "ΔW", meaning: "work done by the system", unit: "J" },
    ],
  },
  {
    id: "ideal-gas",
    name: "Ideal gas law",
    latex: "PV = nRT",
    plain: "PV = nRT",
    meaning: "For a fixed amount of ideal gas. R = 8.314 J/mol·K when P is in pascals and V is in m³.",
    variables: [
      { symbol: "P", meaning: "pressure", unit: "Pa" },
      { symbol: "V", meaning: "volume", unit: "m³" },
      { symbol: "n", meaning: "amount", unit: "mol" },
      { symbol: "T", meaning: "temperature", unit: "K" },
    ],
  },
  {
    id: "kinetic-pressure",
    name: "Pressure of an ideal gas",
    latex: "P = \\tfrac{1}{3}\\rho v_{\\mathrm{rms}}^{2}",
    plain: "P = (1/3)ρ v_rms²",
    meaning: "Connects macroscopic pressure to the mean square speed of molecules.",
    variables: [
      { symbol: "v_rms", meaning: "root mean square speed", unit: "m/s" },
      { symbol: "ρ", meaning: "density", unit: "kg/m³" },
    ],
  },
  {
    id: "rms-temperature",
    name: "RMS speed",
    latex: "v_{\\mathrm{rms}} = \\sqrt{\\dfrac{3RT}{M}}",
    plain: "v_rms = sqrt(3RT / M)",
    meaning: "M is the molar mass in kg/mol, T is in kelvin.",
    variables: [
      { symbol: "R", meaning: "gas constant", unit: "J/mol·K" },
      { symbol: "M", meaning: "molar mass", unit: "kg/mol" },
    ],
  },
  {
    id: "spring-period",
    name: "Spring time period",
    latex: "T = 2\\pi\\sqrt{\\dfrac{m}{k}}",
    plain: "T = 2π sqrt(m/k)",
    meaning: "Period of a mass on a spring, for small oscillations, with the mass of the spring ignored.",
    variables: [
      { symbol: "T", meaning: "time period", unit: "s" },
      { symbol: "m", meaning: "mass", unit: "kg" },
      { symbol: "k", meaning: "spring constant", unit: "N/m" },
    ],
  },
  {
    id: "pendulum-period",
    name: "Simple pendulum",
    latex: "T = 2\\pi\\sqrt{\\dfrac{L}{g}}",
    plain: "T = 2π sqrt(L/g)",
    meaning: "For a small swing. The period does not depend on the mass of the bob.",
    variables: [
      { symbol: "L", meaning: "length", unit: "m" },
      { symbol: "g", meaning: "gravitational acceleration", unit: "m/s²" },
    ],
  },
  {
    id: "shm-velocity",
    name: "SHM velocity",
    latex: "v = \\omega\\sqrt{A^{2} - x^{2}}",
    plain: "v = ω sqrt(A² − x²)",
    meaning: "Speed of a body in simple harmonic motion at displacement x from the centre.",
    variables: [
      { symbol: "A", meaning: "amplitude", unit: "m" },
      { symbol: "ω", meaning: "angular frequency", unit: "rad/s" },
      { symbol: "x", meaning: "displacement", unit: "m" },
    ],
  },
  {
    id: "beats",
    name: "Beat frequency",
    latex: "f_{b} = |f_1 - f_2|",
    plain: "beat frequency = |f1 − f2|",
    meaning: "How many loud-soft cycles you hear each second when two close frequencies sound together.",
    variables: [
      { symbol: "f_b", meaning: "beat frequency", unit: "Hz" },
    ],
  },
  {
    id: "coulomb",
    name: "Coulomb’s law",
    latex: "F = k\\dfrac{|q_1 q_2|}{r^{2}}",
    plain: "F = k |q1 q2| / r²",
    meaning: "In air or vacuum, k = 9 × 10⁹ N m²/C². Like charges repel and unlike charges attract.",
    variables: [
      { symbol: "F", meaning: "force magnitude", unit: "N" },
      { symbol: "q", meaning: "charge", unit: "C" },
      { symbol: "r", meaning: "separation", unit: "m" },
    ],
  },
  {
    id: "electric-field",
    name: "Electric field of a point charge",
    latex: "E = k\\dfrac{|q|}{r^{2}}",
    plain: "E = k |q| / r²",
    meaning: "Field magnitude due to a point charge. Direction is away from a positive charge.",
    variables: [
      { symbol: "E", meaning: "electric field", unit: "N/C" },
    ],
  },
  {
    id: "gauss",
    name: "Gauss’s law",
    latex: "\\Phi = \\dfrac{q_{\\mathrm{encl}}}{\\varepsilon_0}",
    plain: "flux = enclosed charge / ε₀",
    meaning: "The total electric flux through a closed surface equals the enclosed charge divided by ε₀.",
    variables: [
      { symbol: "Φ", meaning: "electric flux", unit: "N m²/C" },
      { symbol: "ε₀", meaning: "permittivity of free space", unit: "C²/N m²" },
    ],
  },
  {
    id: "potential-point",
    name: "Potential of a point charge",
    latex: "V = k\\dfrac{q}{r}",
    plain: "V = kq / r",
    meaning: "Electric potential, with zero chosen at infinity. It is a scalar and keeps the sign of q.",
    variables: [
      { symbol: "V", meaning: "potential", unit: "V" },
    ],
  },
  {
    id: "capacitance",
    name: "Capacitance",
    latex: "C = \\dfrac{Q}{V}",
    plain: "C = Q / V",
    meaning: "Charge stored per volt of potential difference.",
    variables: [
      { symbol: "C", meaning: "capacitance", unit: "F" },
      { symbol: "Q", meaning: "charge", unit: "C" },
      { symbol: "V", meaning: "potential difference", unit: "V" },
    ],
  },
  {
    id: "capacitor-energy",
    name: "Energy in a capacitor",
    latex: "U = \\tfrac{1}{2}CV^{2}",
    plain: "U = (1/2)CV²",
    meaning: "Energy stored in a capacitor.",
    variables: [{ symbol: "U", meaning: "stored energy", unit: "J" }],
  },
  {
    id: "parallel-plate",
    name: "Parallel-plate capacitor",
    latex: "C = \\dfrac{\\varepsilon_0 A}{d}",
    plain: "C = ε₀ A / d",
    meaning: "Capacitance of a parallel-plate capacitor in vacuum. A dielectric of constant K multiplies C by K.",
    variables: [
      { symbol: "A", meaning: "plate area", unit: "m²" },
      { symbol: "d", meaning: "separation", unit: "m" },
    ],
  },
  {
    id: "drift-current",
    name: "Current and drift speed",
    latex: "I = n e A v_{d}",
    plain: "I = neAv_d",
    meaning: "Current in a wire in terms of free-electron density, charge, area, and drift speed.",
    variables: [
      { symbol: "n", meaning: "number of electrons per cubic metre", unit: "m⁻³" },
      { symbol: "e", meaning: "elementary charge", unit: "C" },
      { symbol: "A", meaning: "cross-sectional area", unit: "m²" },
      { symbol: "v_d", meaning: "drift speed", unit: "m/s" },
    ],
  },
  {
    id: "resistivity",
    name: "Resistance and resistivity",
    latex: "R = \\rho\\dfrac{l}{A}",
    plain: "R = ρl / A",
    meaning: "Resistance of a uniform wire. ρ is a property of the material.",
    variables: [
      { symbol: "ρ", meaning: "resistivity", unit: "Ω m" },
      { symbol: "l", meaning: "length", unit: "m" },
      { symbol: "A", meaning: "area", unit: "m²" },
    ],
  },
  {
    id: "wire-force",
    name: "Force on a current-carrying wire",
    latex: "F = IlB\\sin\\theta",
    plain: "F = IlB sin θ",
    meaning: "Force on a straight wire in a magnetic field. θ is the angle between the wire and the field.",
    variables: [
      { symbol: "I", meaning: "current", unit: "A" },
      { symbol: "l", meaning: "length", unit: "m" },
      { symbol: "B", meaning: "magnetic field", unit: "T" },
    ],
  },
  {
    id: "lorentz",
    name: "Force on a moving charge",
    latex: "F = qvB\\sin\\theta",
    plain: "F = qvB sin θ",
    meaning: "Magnetic force on a charge. It is zero when the velocity is parallel to the field, and it does no work.",
    variables: [
      { symbol: "q", meaning: "charge", unit: "C" },
      { symbol: "v", meaning: "speed", unit: "m/s" },
      { symbol: "B", meaning: "magnetic field", unit: "T" },
    ],
  },
  {
    id: "faraday",
    name: "Faraday’s law",
    latex: "\\mathcal{E} = -\\dfrac{\\Delta\\Phi}{\\Delta t}",
    plain: "induced emf = − change in flux / time",
    meaning: "A changing magnetic flux induces an emf. The minus sign is Lenz’s law: the induced current opposes the change that causes it.",
    variables: [
      { symbol: "ε", meaning: "induced emf", unit: "V" },
      { symbol: "Φ", meaning: "magnetic flux", unit: "Wb" },
    ],
  },
  {
    id: "ac-rms",
    name: "RMS values",
    latex: "V_{\\mathrm{rms}} = \\dfrac{V_0}{\\sqrt{2}}, \\quad I_{\\mathrm{rms}} = \\dfrac{I_0}{\\sqrt{2}}",
    plain: "V_rms = V₀ / √2",
    meaning: "Household AC values, such as 220 V, are RMS values, not the peak.",
    variables: [
      { symbol: "V_0", meaning: "peak voltage", unit: "V" },
    ],
  },
  {
    id: "impedance",
    name: "Series LCR impedance",
    latex: "Z = \\sqrt{R^{2} + (X_L - X_C)^{2}}",
    plain: "Z = sqrt(R² + (X_L − X_C)²)",
    meaning: "X_L = ωL and X_C = 1/(ωC). At resonance, X_L = X_C and Z = R.",
    variables: [
      { symbol: "Z", meaning: "impedance", unit: "Ω" },
      { symbol: "X_L", meaning: "inductive reactance", unit: "Ω" },
      { symbol: "X_C", meaning: "capacitive reactance", unit: "Ω" },
    ],
  },
  {
    id: "transformer",
    name: "Ideal transformer",
    latex: "\\dfrac{V_s}{V_p} = \\dfrac{N_s}{N_p}",
    plain: "Vs / Vp = Ns / Np",
    meaning: "For an ideal transformer. A step-down transformer has fewer turns on the secondary.",
    variables: [
      { symbol: "V_p, V_s", meaning: "primary and secondary voltages", unit: "V" },
      { symbol: "N_p, N_s", meaning: "primary and secondary turns", unit: "no unit" },
    ],
  },
  {
    id: "em-speed",
    name: "Speed of an electromagnetic wave",
    latex: "c = \\dfrac{1}{\\sqrt{\\mu_0\\varepsilon_0}}",
    plain: "c = 1 / sqrt(μ₀ε₀)",
    meaning: "All electromagnetic waves in vacuum travel at 3.00 × 10⁸ m/s.",
    variables: [
      { symbol: "c", meaning: "speed of light", unit: "m/s" },
    ],
  },
  {
    id: "young-fringe",
    name: "Fringe width",
    latex: "\\beta = \\dfrac{\\lambda D}{d}",
    plain: "β = λD / d",
    meaning: "Distance between bright fringes in Young’s double-slit experiment.",
    variables: [
      { symbol: "β", meaning: "fringe width", unit: "m" },
      { symbol: "λ", meaning: "wavelength", unit: "m" },
      { symbol: "D", meaning: "distance to the screen", unit: "m" },
      { symbol: "d", meaning: "slit separation", unit: "m" },
    ],
  },
  {
    id: "einstein-photo",
    name: "Photoelectric equation",
    latex: "K_{\\max} = hf - \\phi",
    plain: "K_max = hf − φ",
    meaning: "Maximum kinetic energy of a photoelectron. No electrons leave if hf is less than the work function φ. h = 6.626 × 10⁻³⁴ J s.",
    variables: [
      { symbol: "f", meaning: "frequency of light", unit: "Hz" },
      { symbol: "φ", meaning: "work function", unit: "J" },
      { symbol: "K_max", meaning: "maximum kinetic energy", unit: "J" },
    ],
  },
  {
    id: "de-broglie",
    name: "de Broglie wavelength",
    latex: "\\lambda = \\dfrac{h}{p}",
    plain: "λ = h / p",
    meaning: "Every moving particle has a wavelength. p is momentum.",
    variables: [
      { symbol: "λ", meaning: "wavelength", unit: "m" },
      { symbol: "p", meaning: "momentum", unit: "kg m/s" },
      { symbol: "h", meaning: "Planck’s constant", unit: "J s" },
    ],
  },
  {
    id: "bohr-energy",
    name: "Bohr energy levels",
    latex: "E_n = -\\dfrac{13.6\\,\\mathrm{eV}}{n^{2}}",
    plain: "E_n = −13.6 eV / n²",
    meaning: "Energy of the electron in hydrogen. n = 1 is the ground state. A photon is emitted when the electron falls to a lower n.",
    variables: [
      { symbol: "n", meaning: "principal quantum number", unit: "1, 2, 3, …" },
      { symbol: "E_n", meaning: "energy of level n", unit: "eV" },
    ],
  },
  {
    id: "half-life",
    name: "Radioactive remaining fraction",
    latex: "N = N_0 \\left(\\tfrac{1}{2}\\right)^{t/T}",
    plain: "N = N₀ (1/2)^(t/T)",
    meaning: "T is the half-life. After n half-lives, N = N₀ / 2ⁿ.",
    variables: [
      { symbol: "N_0", meaning: "initial number of nuclei", unit: "count" },
      { symbol: "T", meaning: "half-life", unit: "s" },
      { symbol: "t", meaning: "time", unit: "s" },
    ],
  },
  {
    id: "mass-defect",
    name: "Binding energy",
    latex: "E = \\Delta m\\, c^{2}",
    plain: "E = Δm c²",
    meaning: "Binding energy comes from the mass defect. 1 u corresponds to 931 MeV.",
    variables: [
      { symbol: "Δm", meaning: "mass defect", unit: "kg" },
      { symbol: "c", meaning: "speed of light", unit: "m/s" },
    ],
  },
];

const byId = new Map(formulas.map((formula) => [formula.id, formula]));

export function getFormula(id: string): Formula | undefined {
  return byId.get(id);
}

export function formulasFor(ids: string[]): Formula[] {
  return ids.map((id) => {
    const formula = byId.get(id);
    if (!formula) {
      throw new Error(`Unknown formula id: ${id}`);
    }
    return formula;
  });
}
