import type { Chapter } from "../types";

export const middleChapters: Chapter[] = [
  {
    id: "c6-measure",
    grade: 6,
    title: "Measurement",
    promise: "Science needs standard units so everyone means the same length.",
    scopeNote: "Class 6 measurement. The metre is the SI unit of length.",
    topics: [
      {
        id: "c6-units",
        title: "Standard units",
        aliases: ["unit", "metre", "measurement", "si"],
        idea: "A measurement needs a number and a unit. The standard unit of length in science is the metre.",
        younger: "Saying a desk is “5” does not tell us 5 what. Five metres and five centimetres are different. Scientists use standard units so the number has a meaning.",
        example: "A pencil may be about 15 cm long. A classroom may be about 8 m long.",
        formulaIds: [],
        mistake: { wrong: "A bigger number always means a longer object, even if the units differ.", right: "200 cm is 2 m, so you must convert before you compare." },
        check: { question: "Why is the unit as important as the number?", answer: "The same number can mean different lengths if the units are different." },
        keyPoints: ["Every measurement needs a unit.", "The metre is the standard unit of length.", "Convert units before you compare."],
        practice: [{ id: "c6-units-p1", question: "Which is longer, 2 m or 150 cm?", hint: "1 m = 100 cm.", answer: "2 m is 200 cm, so 2 m is longer." }],
        quiz: [
          { id: "c6-units-q1", question: "The standard scientific unit of length is the…", choices: ["metre", "minute", "kilogram", "newton"], answerIndex: 0, explanation: "Length is measured in metres in SI." },
          { id: "c6-units-q2", question: "150 cm is the same as…", choices: ["1.5 m", "15 m", "150 m", "0.15 m"], answerIndex: 0, explanation: "100 cm = 1 m, so 150 cm = 1.5 m." },
        ],
      },
      {
        id: "c6-length",
        title: "Measuring length",
        aliases: ["ruler", "length", "scale"],
        idea: "A ruler measures length. Place the zero mark at one end and read the mark at the other end.",
        younger: "If you start at the 1 cm mark by mistake, the reading will be too large. Keep your eye above the mark you are reading.",
        example: "A notebook measured from 0 cm to 21 cm is 21 cm long.",
        formulaIds: [],
        mistake: { wrong: "You should start measuring from the worn end of a broken ruler without correcting the zero.", right: "If the zero is damaged, start at a clear mark and subtract that starting reading." },
        check: { question: "A pencil runs from the 2 cm mark to the 12 cm mark. How long is it?", answer: "10 cm." },
        keyPoints: ["Use a standard scale.", "Line up the zero carefully.", "Subtract the starting mark if you do not start at zero."],
        practice: [{ id: "c6-length-p1", question: "A book runs from 3 cm to 28 cm on a ruler. What is its length?", hint: "Subtract the starting reading.", answer: "25 cm." }],
        quiz: [
          { id: "c6-length-q1", question: "If an object runs from 1 cm to 9 cm, its length is…", choices: ["8 cm", "9 cm", "10 cm", "1 cm"], answerIndex: 0, explanation: "Length = 9 − 1 = 8 cm." },
        ],
      },
    ],
  },
  {
    id: "c6-motion",
    grade: 6,
    title: "Motion and speed",
    promise: "Speed tells how fast distance is covered.",
    scopeNote: "Class 6 uses speed = distance / time. Velocity as a vector is developed later.",
    topics: [
      {
        id: "c6-speed",
        title: "Speed",
        aliases: ["speed", "velocity", "how fast"],
        idea: "Speed is the distance covered divided by the time taken. It has no direction. Velocity, which you will use more carefully later, includes direction.",
        younger: "If a bicycle covers more metres in the same time, it has a greater speed. In words, speed = distance ÷ time.",
        senior: "Average velocity uses displacement, not distance. Do not swap those words when the path bends.",
        example: "A child who walks 100 m in 50 s has a speed of 2 m/s.",
        formulaIds: ["speed"],
        mistake: { wrong: "Speed and velocity are identical even when the path curves back to the start.", right: "Speed uses distance. Velocity uses displacement and a direction." },
        check: { question: "A car covers 20 m in 4 s. What is its speed?", answer: "5 m/s." },
        keyPoints: ["Speed = distance / time.", "The usual unit is m/s.", "Speed does not include direction.", "Velocity does include direction."],
        sketch: "motion",
        table: {
          caption: "Two different ideas",
          headers: ["", "Speed", "Velocity"],
          rows: [
            ["Tells us", "How fast", "How fast and which way"],
            ["Uses", "Distance", "Displacement"],
          ],
        },
        worked: {
          prompt: "A cyclist covers 100 m in 20 s. What is the speed?",
          formulaId: "speed",
          known: { s: { value: 100, unit: "m" }, t: { value: 20, unit: "s" } },
          find: "v",
          after: "The speed is 5 m/s. We do not yet have a direction, so this is speed, not a full velocity.",
        },
        practice: [
          {
            id: "c6-speed-p1",
            question: "A runner covers 400 m in 80 s. Find the speed.",
            hint: "Divide distance by time.",
            answer: "5 m/s.",
            worked: { formulaId: "speed", known: { s: { value: 400, unit: "m" }, t: { value: 80, unit: "s" } }, find: "v" },
          },
        ],
        quiz: [
          { id: "c6-speed-q1", question: "Speed is…", choices: ["distance ÷ time", "time ÷ mass", "force × area", "mass × height"], answerIndex: 0, explanation: "That is the Class 6 definition." },
          { id: "c6-speed-q2", question: "Which unit is a unit of speed?", choices: ["m/s", "kg", "N", "°C"], answerIndex: 0, explanation: "Metres per second is distance divided by time." },
        ],
      },
      {
        id: "c6-distance-time",
        title: "Distance and time",
        aliases: ["distance", "time", "uniform motion"],
        idea: "If the speed stays the same, equal distances are covered in equal times. That is uniform motion.",
        younger: "A bus at a steady 10 m/s covers 10 m in every second. If the speed keeps changing, the motion is non-uniform.",
        example: "A ceiling fan point can keep changing speed as it starts, so that motion is not uniform.",
        formulaIds: ["speed"],
        mistake: { wrong: "Uniform motion means the object is not moving.", right: "Uniform motion means the speed is steady." },
        check: { question: "A toy covers 2 m every second. Is the motion uniform?", answer: "Yes, because equal distances take equal times." },
        keyPoints: ["Uniform motion has steady speed.", "Non-uniform motion has changing speed.", "Distance and time must be measured for the same part of the trip."],
        practice: [{ id: "c6-distance-time-p1", question: "A scooter moves at 8 m/s. How far does it go in 5 s?", hint: "Distance = speed × time.", answer: "40 m.", worked: { formulaId: "speed", known: { v: { value: 8, unit: "m/s" }, t: { value: 5, unit: "s" } }, find: "s" } }],
        quiz: [
          { id: "c6-distance-time-q1", question: "Uniform motion means the speed is…", choices: ["steady", "always zero", "always increasing", "measured in kilograms"], answerIndex: 0, explanation: "Equal distances in equal times." },
        ],
      },
    ],
  },
  {
    id: "c6-electric",
    grade: 6,
    title: "Light, circuits, and magnets",
    promise: "A complete circuit lets current flow. Magnets attract some metals.",
    scopeNote: "Class 6 introductions. Ohm’s law is for Class 10.",
    topics: [
      {
        id: "c6-circuit",
        title: "A simple circuit",
        aliases: ["circuit", "bulb", "cell", "switch", "electricity"],
        idea: "A cell, wires, and a bulb make a circuit. The bulb glows only when the path is complete.",
        younger: "A switch can open a gap. An open gap stops the current, so the bulb goes out. A closed switch completes the path.",
        example: "A torch lights when its switch closes the circuit inside.",
        formulaIds: [],
        mistake: { wrong: "A bulb can glow even if one wire is disconnected.", right: "The conducting path has to be complete." },
        check: { question: "What happens to the bulb if you open the switch?", answer: "It stops glowing, because the circuit is broken." },
        keyPoints: ["A circuit needs a complete path.", "A cell pushes the current.", "An open switch stops the current.", "Wires are conductors."],
        sketch: "circuit",
        practice: [{ id: "c6-circuit-p1", question: "Why does a torch stop working when the cell is removed?", hint: "What provided the push?", answer: "The cell was the source. Without it the circuit has no source." }],
        quiz: [
          { id: "c6-circuit-q1", question: "A bulb in a circuit glows when the path is…", choices: ["complete", "open", "made of plastic only", "broken on purpose"], answerIndex: 0, explanation: "Current needs a closed path." },
        ],
      },
      {
        id: "c6-magnet",
        title: "Magnets",
        aliases: ["magnet", "north pole", "south pole", "attract"],
        idea: "A magnet has a north pole and a south pole. Opposite poles attract. Like poles repel.",
        younger: "A magnet can pick up iron, but not plastic or wood. If you cut a bar magnet, each piece still has two poles. You cannot get a single north pole by itself.",
        example: "A fridge magnet sticks to the steel door and not to the plastic handle.",
        formulaIds: [],
        mistake: { wrong: "North repels south.", right: "Opposite poles attract. Like poles repel." },
        check: { question: "Do two north poles attract or repel?", answer: "They repel." },
        keyPoints: ["Magnets attract iron and steel.", "Opposite poles attract.", "Like poles repel.", "Every magnet has two poles."],
        sketch: "magnet",
        practice: [{ id: "c6-magnet-p1", question: "Will a magnet attract a wooden ruler?", hint: "Wood is not a magnetic metal.", answer: "No." }],
        quiz: [
          { id: "c6-magnet-q1", question: "Like poles of two magnets…", choices: ["repel", "always attract", "remove gravity", "make the magnets weightless"], answerIndex: 0, explanation: "North repels north, and south repels south." },
          { id: "c6-magnet-q2", question: "A magnet does not attract…", choices: ["a plastic spoon", "an iron nail", "a steel pin", "an iron clip"], answerIndex: 0, explanation: "Plastic is not a magnetic material." },
        ],
      },
    ],
  },
  {
    id: "c7-speed",
    grade: 7,
    title: "Speed and time",
    promise: "Average speed uses the whole journey, not a casual average of two speeds.",
    scopeNote: "Class 7 speed. Keep kilometres and hours consistent.",
    topics: [
      {
        id: "c7-speed",
        title: "Calculating speed",
        aliases: ["speed", "velocity", "km/h"],
        idea: "Speed is distance divided by time. If the distance is in kilometres and the time is in hours, the speed is in km/h.",
        younger: "A bus that covers 120 km in 2 hours has a speed of 60 km/h. Do not mix kilometres with seconds unless you convert.",
        example: "Walking 1.5 km in half an hour is a speed of 3 km/h.",
        formulaIds: ["speed", "velocity"],
        mistake: { wrong: "120 km in 2 hours is 120 × 2 = 240 km/h.", right: "Divide: 120 / 2 = 60 km/h." },
        check: { question: "What is the speed if a car covers 90 km in 3 hours?", answer: "30 km/h." },
        keyPoints: ["Speed = distance / time.", "Matching units give a matching speed unit.", "km/h and m/s are both speeds, but they are not the same number."],
        sketch: "motion",
        worked: {
          prompt: "A bus covers 120 km in 2 hours. What is its speed?",
          formulaId: "speed",
          known: { s: { value: 120, unit: "km" }, t: { value: 2, unit: "h" } },
          find: "v",
        },
        practice: [{ id: "c7-speed-p1", question: "A train covers 150 km in 3 hours. Find its speed.", hint: "Divide distance by time and keep km and hours.", answer: "50 km/h.", worked: { formulaId: "speed", known: { s: { value: 150, unit: "km" }, t: { value: 3, unit: "h" } }, find: "v" } }],
        quiz: [
          { id: "c7-speed-q1", question: "A scooter covers 40 km in 2 hours. Its speed is…", choices: ["20 km/h", "80 km/h", "42 km/h", "2 km/h"], answerIndex: 0, explanation: "40 / 2 = 20 km/h." },
        ],
      },
      {
        id: "c7-average",
        title: "Average speed",
        aliases: ["average speed", "total distance"],
        idea: "Average speed is total distance divided by total time. It is not the ordinary average of two speeds unless the times are equal.",
        younger: "If you go fast for a long time and slow for a short time, the fast part counts more. Add the distances, add the times, then divide.",
        example: "30 km/h for 2 hours and 60 km/h for 1 hour gives 120 km in 3 hours, so the average speed is 40 km/h, not 45 km/h.",
        formulaIds: ["average-speed"],
        mistake: { wrong: "Average speed is always the average of the two speed numbers.", right: "Use total distance and total time. The plain average works only when the times match." },
        check: { question: "You travel 20 km in 1 hour, then 20 km in 1 hour. What is the average speed?", answer: "20 km/h. Here the plain average happens to agree because the times are equal." },
        keyPoints: ["Average speed = total distance / total time.", "Do not average the speeds unless the times are equal.", "A stop adds time but no distance, so it lowers the average speed."],
        practice: [{ id: "c7-average-p1", question: "A car goes 30 km/h for 2 hours and 60 km/h for 1 hour. Find the average speed.", hint: "Find each distance, then divide the total distance by 3 hours.", answer: "40 km/h." }],
        quiz: [
          { id: "c7-average-q1", question: "Average speed uses…", choices: ["total distance and total time", "only the fastest moment", "mass and force", "the larger speed only"], answerIndex: 0, explanation: "The definition is a ratio of totals." },
        ],
      },
    ],
  },
  {
    id: "c7-heat",
    grade: 7,
    title: "Heat",
    promise: "Temperature tells how hot something is. Heat is energy moving because of a temperature difference.",
    scopeNote: "Class 7 heat, before the full specific-heat calculations of later classes.",
    topics: [
      {
        id: "c7-temperature",
        title: "Temperature and heat",
        aliases: ["temperature", "heat", "thermometer"],
        idea: "Temperature measures how hot an object is. Heat is the energy transferred from a hotter object to a cooler one.",
        younger: "A thermometer reads temperature, not “amount of heat” by itself. A large pot of warm water can hold more heat energy than a cup of hotter water.",
        example: "Clinical thermometers measure body temperature. Room thermometers measure the air.",
        formulaIds: [],
        mistake: { wrong: "The hotter object always contains more heat energy, whatever its size.", right: "Temperature and the amount of heat energy are different. Size matters." },
        check: { question: "Does a thermometer measure temperature or the total heat in a large lake?", answer: "It measures temperature." },
        keyPoints: ["Temperature tells how hot.", "Heat is energy in transit.", "A thermometer is for temperature.", "A bigger warm object can store more energy than a smaller hotter one."],
        sketch: "heat",
        practice: [{ id: "c7-temperature-p1", question: "Why can a bathtub of warm water warm a room more than a cup of hotter tea?", hint: "Think about the amount of water.", answer: "The bathtub holds much more water, so it can give out more heat even at a lower temperature." }],
        quiz: [
          { id: "c7-temperature-q1", question: "A thermometer measures…", choices: ["temperature", "speed", "resistance", "mass"], answerIndex: 0, explanation: "Temperature is how hot the object is." },
        ],
      },
      {
        id: "c7-flow",
        title: "Heat flow",
        aliases: ["conduction", "heat flow", "conductor of heat"],
        idea: "Heat flows from higher temperature to lower temperature. Metals usually conduct heat well.",
        younger: "A metal spoon in hot soup becomes hot along its handle. A wooden spoon does this much more slowly. Wood is a poorer conductor.",
        example: "Cooking pans are metal so heat reaches the food. Their handles are often plastic or wood.",
        formulaIds: [],
        mistake: { wrong: "Heat naturally flows from a cold object into a hot one.", right: "By itself, heat flows from hot to cold." },
        check: { question: "Why can a metal spoon feel hotter than a wooden one in the same soup?", answer: "Metal conducts heat to your hand more quickly." },
        keyPoints: ["Heat flows hot to cold.", "Metals are good conductors of heat.", "Wood and plastic are poorer conductors."],
        practice: [{ id: "c7-flow-p1", question: "Which spoon heats your fingers sooner in hot soup, metal or wood?", hint: "Which is the better conductor?", answer: "The metal spoon." }],
        quiz: [
          { id: "c7-flow-q1", question: "Heat flows by itself from…", choices: ["hot to cold", "cold to hot", "light to sound", "north to south"], answerIndex: 0, explanation: "The hotter object loses heat to the cooler one." },
        ],
      },
    ],
  },
  {
    id: "c7-current",
    grade: 7,
    title: "Current and reflection",
    promise: "Current is a flow of charge. Mirrors reflect light in a regular way.",
    scopeNote: "Class 7 descriptions. The mirror formula and Ohm’s law come in Class 10.",
    topics: [
      {
        id: "c7-current",
        title: "Electric current",
        aliases: ["current", "circuit", "cell", "battery"],
        idea: "An electric current is a flow of electric charge. In a simple circuit a cell keeps that flow going.",
        younger: "More cells in a simple torch can make the bulb brighter, but only if they are connected the right way and the bulb can bear it. A broken wire stops the flow.",
        example: "A closed switch lets current reach a bulb. An open switch does not.",
        formulaIds: [],
        mistake: { wrong: "Current is used up completely by the first wire and never returns.", right: "In a simple series circuit the same current goes all the way around." },
        check: { question: "What happens to the current when the switch is opened?", answer: "The current stops, because the path is broken." },
        keyPoints: ["Current is a flow of charge.", "A cell can drive the current.", "The circuit must be closed.", "In a single loop, the current is the same all around."],
        sketch: "circuit",
        practice: [{ id: "c7-current-p1", question: "Why does a bulb go out when one wire comes loose?", hint: "Is the path complete?", answer: "The circuit is open, so charge cannot keep flowing." }],
        quiz: [
          { id: "c7-current-q1", question: "Electric current is a flow of…", choices: ["charge", "shadows", "air only", "magnets"], answerIndex: 0, explanation: "That is the definition used in this class." },
        ],
      },
      {
        id: "c7-reflection",
        title: "Reflection",
        aliases: ["reflection", "mirror", "incident ray"],
        idea: "Reflection is the bouncing of light from a surface. On a smooth mirror, the angle of incidence equals the angle of reflection.",
        younger: "Both angles are measured from the normal, the line at 90° to the mirror, not from the mirror itself.",
        example: "A periscope uses two plane mirrors to send light by reflection.",
        formulaIds: [],
        mistake: { wrong: "The angles are measured from the mirror surface in the school law.", right: "Measure both angles from the normal." },
        check: { question: "If the angle of incidence is 30°, what is the angle of reflection from a plane mirror?", answer: "30°." },
        keyPoints: ["Light can bounce off a mirror.", "Angle of incidence equals angle of reflection.", "Angles are measured from the normal."],
        sketch: "mirror",
        practice: [{ id: "c7-reflection-p1", question: "The incident ray makes 40° with the normal. What angle does the reflected ray make with the normal?", hint: "The two angles are equal.", answer: "40°." }],
        quiz: [
          { id: "c7-reflection-q1", question: "The angle of reflection is measured from the…", choices: ["normal", "floor of the room", "wire", "north pole"], answerIndex: 0, explanation: "The normal is perpendicular to the mirror." },
        ],
      },
    ],
  },
  {
    id: "c8-pressure",
    grade: 8,
    title: "Force and pressure",
    promise: "Pressure is force spread over an area.",
    scopeNote: "Class 8 pressure P = F/A, and a first look at liquid pressure.",
    topics: [
      {
        id: "c8-pressure",
        title: "Pressure",
        aliases: ["pressure", "area", "force"],
        idea: "Pressure is the force acting perpendicular to a surface, divided by the area. The same force on a smaller area makes a larger pressure.",
        younger: "A sharp needle goes into cloth more easily than a blunt end because the area is tiny, so the pressure is large. Wide camel feet keep the pressure on sand smaller.",
        example: "A 20 N force on an area of 0.04 m² produces a pressure of 500 Pa.",
        formulaIds: ["pressure"],
        mistake: { wrong: "Pressure and force are the same quantity.", right: "Force is in newtons. Pressure is force per area, in pascals." },
        check: { question: "Why does a sharp knife cut better than a blunt one?", answer: "The sharp edge has a smaller area, so the pressure is greater for the same force." },
        keyPoints: ["Pressure = force / area.", "The SI unit is the pascal.", "Smaller area means larger pressure for the same force."],
        worked: {
          prompt: "A force of 20 N acts on an area of 0.04 m². Find the pressure.",
          formulaId: "pressure",
          known: { F: { value: 20, unit: "N" }, A: { value: 0.04, unit: "m²" } },
          find: "P",
        },
        practice: [{ id: "c8-pressure-p1", question: "A 10 N force acts on 0.02 m². Find the pressure.", hint: "Divide force by area.", answer: "500 Pa.", worked: { formulaId: "pressure", known: { F: { value: 10, unit: "N" }, A: { value: 0.02, unit: "m²" } }, find: "P" } }],
        quiz: [
          { id: "c8-pressure-q1", question: "Pressure increases when the same force acts on…", choices: ["a smaller area", "a larger area", "a longer time only", "a cooler surface only"], answerIndex: 0, explanation: "P = F/A, so a smaller area raises P." },
        ],
      },
      {
        id: "c8-liquid",
        title: "Pressure in a liquid",
        aliases: ["liquid pressure", "depth", "dam"],
        idea: "Pressure in a still liquid increases with depth. At the same depth, it acts in all directions.",
        younger: "A dam is thicker at the bottom because the water pressure is greater there. The formula used later is P = hρg.",
        example: "Your ears feel more pressure when you dive deeper in a pool.",
        formulaIds: ["liquid-pressure"],
        mistake: { wrong: "Liquid pressure depends only on the shape of the container.", right: "For a still liquid, the depth and the density matter, not the container’s width." },
        check: { question: "Where is water pressure greater, at the surface or at the bottom of a deep pool?", answer: "At the bottom." },
        keyPoints: ["Deeper means greater liquid pressure.", "Denser liquids press more at the same depth.", "Dams are built stronger near the base."],
        practice: [{ id: "c8-liquid-p1", question: "Why is a dam thicker at the bottom?", hint: "Compare the pressure.", answer: "The water pressure is greater at greater depth." }],
        quiz: [
          { id: "c8-liquid-q1", question: "In a still liquid, pressure is greater…", choices: ["deeper down", "at the open surface", "in a wider beaker at the same depth", "where the liquid is brightest"], answerIndex: 0, explanation: "Pressure increases with depth." },
        ],
      },
    ],
  },
  {
    id: "c8-friction-sound",
    grade: 8,
    title: "Friction and sound",
    promise: "Friction opposes relative motion. Sound is a vibration that needs a medium.",
    scopeNote: "Class 8. The friction formula f = μN is used carefully in Class 11.",
    topics: [
      {
        id: "c8-friction",
        title: "Friction",
        aliases: ["friction", "static friction", "sliding"],
        idea: "Friction opposes the relative motion, or the tendency to move, between surfaces. It depends on how hard the surfaces are pressed together and on the materials.",
        younger: "Static friction can keep a block from starting to slide. Once it slides, kinetic friction opposes the sliding. Rolling usually meets less friction than sliding.",
        example: "It is harder to start pushing a heavy cupboard than to keep it slowly moving.",
        formulaIds: ["friction"],
        mistake: { wrong: "Friction always points in the direction of motion.", right: "It opposes the sliding, so it points opposite to the relative motion." },
        check: { question: "Which way does friction point on a book you are sliding to the right?", answer: "To the left, opposite the slide." },
        keyPoints: ["Friction opposes sliding.", "Pressing surfaces harder can increase friction.", "Static friction acts before sliding starts.", "Lubrication reduces friction."],
        practice: [{ id: "c8-friction-p1", question: "Why does oil help a squeaky hinge?", hint: "What does oil do to friction?", answer: "It reduces friction between the moving parts." }],
        quiz: [
          { id: "c8-friction-q1", question: "Sliding friction acts…", choices: ["opposite the slide", "in the direction of the slide", "only upward", "only on liquids"], answerIndex: 0, explanation: "Friction opposes relative motion." },
        ],
      },
      {
        id: "c8-sound",
        title: "How sound is made",
        aliases: ["sound", "vibration", "pitch", "loudness", "frequency"],
        idea: "Sound is produced by vibration and travels as a wave through a medium. Loudness depends on amplitude. Pitch depends on frequency.",
        younger: "A bigger vibration sounds louder. A higher frequency sounds higher in pitch. Sound cannot travel through a vacuum.",
        example: "A tight short string on a guitar usually gives a higher note than a loose long one.",
        formulaIds: ["wave-speed"],
        mistake: { wrong: "Pitch and loudness are the same thing.", right: "Pitch follows frequency. Loudness follows amplitude." },
        check: { question: "What does a sound need in order to travel from a bell to your ear?", answer: "A medium, such as air." },
        keyPoints: ["Sound comes from vibrations.", "It needs a medium.", "Loudness follows amplitude.", "Pitch follows frequency.", "Wave speed = frequency × wavelength."],
        sketch: "wave",
        practice: [{ id: "c8-sound-p1", question: "A wave has frequency 200 Hz and wavelength 1.7 m. Find the speed.", hint: "Multiply frequency by wavelength.", answer: "340 m/s.", worked: { formulaId: "wave-speed", known: { f: { value: 200, unit: "Hz" }, lambda: { value: 1.7, unit: "m" } }, find: "v" } }],
        quiz: [
          { id: "c8-sound-q1", question: "Pitch depends mainly on…", choices: ["frequency", "mass of the listener", "colour", "area"], answerIndex: 0, explanation: "Higher frequency means a higher pitch." },
          { id: "c8-sound-q2", question: "Sound cannot travel through…", choices: ["a vacuum", "air", "water", "a steel rail"], answerIndex: 0, explanation: "There is no medium in a vacuum to carry the vibration." },
        ],
      },
    ],
  },
  {
    id: "c8-sky",
    grade: 8,
    title: "Light and the sky",
    promise: "A plane mirror reflects regularly. The solar system is held together by gravity.",
    scopeNote: "Qualitative Class 8 astronomy. Orbital formulas are for Class 11.",
    topics: [
      {
        id: "c8-plane-mirror",
        title: "A plane mirror",
        aliases: ["plane mirror", "image", "lateral inversion"],
        idea: "A plane mirror forms an image that is virtual, erect, the same size, and as far behind the mirror as the object is in front. The image is laterally inverted.",
        younger: "Virtual means the rays do not really meet behind the mirror. You see the image because the reflected rays enter your eyes as if they came from there.",
        example: "The word AMBULANCE is reversed on the front of the vehicle so a driver looking in a mirror can read it.",
        formulaIds: [],
        mistake: { wrong: "A plane mirror turns the image upside down in ordinary face-on viewing.", right: "It reverses left and right. It does not invert top and bottom." },
        check: { question: "An object is 30 cm in front of a plane mirror. How far behind the mirror does the image appear?", answer: "30 cm." },
        keyPoints: ["The image is virtual and erect.", "Image size equals object size.", "Image distance equals object distance.", "Left and right are swapped."],
        sketch: "mirror",
        practice: [{ id: "c8-plane-mirror-p1", question: "You stand 2 m in front of a plane mirror. What is the distance between you and your image?", hint: "The image is 2 m behind the mirror.", answer: "4 m." }],
        quiz: [
          { id: "c8-plane-mirror-q1", question: "A plane-mirror image is…", choices: ["virtual and the same size", "real and smaller", "real and upside down", "formed on a screen behind the mirror"], answerIndex: 0, explanation: "Plane-mirror images are virtual, erect, and the same size." },
        ],
      },
      {
        id: "c8-solar",
        title: "The solar system",
        aliases: ["solar system", "planet", "orbit", "gravity"],
        idea: "Earth and the other planets orbit the Sun. Gravity keeps them in orbit. The Moon orbits Earth.",
        younger: "A year is about the time Earth takes to go once around the Sun. A day is about the time Earth takes to spin once. Stars are distant suns, not planets.",
        example: "We see different constellations in different months because Earth has moved around the Sun.",
        formulaIds: [],
        mistake: { wrong: "The Sun orbits Earth once a day.", right: "Earth spins once a day and orbits the Sun once a year." },
        check: { question: "What force keeps Earth in its orbit around the Sun?", answer: "Gravity." },
        keyPoints: ["Planets orbit the Sun.", "Gravity holds the orbits.", "Earth spins to make day and night.", "The Moon orbits Earth."],
        sketch: "gravity",
        practice: [{ id: "c8-solar-p1", question: "What motion of Earth gives us day and night?", hint: "It is not the yearly orbit.", answer: "Earth spinning on its axis." }],
        quiz: [
          { id: "c8-solar-q1", question: "Earth orbits…", choices: ["the Sun", "the Moon", "a single star other than the Sun once a day", "the north pole of a magnet"], answerIndex: 0, explanation: "Earth is a planet of the Sun." },
        ],
      },
    ],
  },
];
