import type { Chapter } from "../types";

export const primaryChapters: Chapter[] = [
  {
    id: "c1-forces",
    grade: 1,
    title: "Pushes and pulls",
    promise: "You can move things by pushing or pulling.",
    scopeNote: "Everyday forces for Class 1. No formulas yet.",
    topics: [
      {
        id: "c1-push",
        title: "A push",
        aliases: ["push", "pushing", "force"],
        idea: "A push moves something away from you. A harder push can move a heavier thing.",
        younger: "A push sends something away from your hands. You push a swing to make it go. If the box is too heavy, your push may not be enough.",
        example: "You push a toy car and it rolls away across the floor.",
        formulaIds: [],
        mistake: { wrong: "If a box does not move, nobody pushed it.", right: "You can push a heavy box and it can still stay still." },
        check: { question: "Does a push send a toy toward you or away from you?", answer: "Away from you." },
        keyPoints: ["A push moves something away from you.", "A bigger push can move a heavier object.", "Some objects stay still if the push is too small."],
        sketch: "push",
        practice: [{ id: "c1-push-p1", question: "Name one push you do at home.", hint: "Think about a door or a swing.", answer: "Pushing a door open, or pushing a swing, is a push." }],
        quiz: [
          { id: "c1-push-q1", question: "A push moves an object…", choices: ["away from you", "only upward", "only at night", "into your hand"], answerIndex: 0, explanation: "A push sends the object away from you." },
          { id: "c1-push-q2", question: "A heavy box does not move. What can be true?", choices: ["The push was too small", "Pushes only work on balls", "The box has no size", "Pushes need darkness"], answerIndex: 0, explanation: "A push can be real and still be too small to move a heavy box." },
        ],
      },
      {
        id: "c1-pull",
        title: "A pull",
        aliases: ["pull", "pulling"],
        idea: "A pull moves something toward you.",
        younger: "A pull brings something closer. Opening a drawer toward you is a pull. Tugging a rope in a tug of war is a pull.",
        example: "You pull a chair closer so you can sit down.",
        formulaIds: [],
        mistake: { wrong: "Opening a door toward yourself is a push.", right: "If the door comes toward you, you are pulling it." },
        check: { question: "Is drawing a bucket up from a well a push or a pull?", answer: "A pull." },
        keyPoints: ["A pull moves something toward you.", "Ropes are often used for pulls.", "Push and pull are both ways to move things."],
        practice: [{ id: "c1-pull-p1", question: "Is closing a drawer toward you a push or a pull?", hint: "Watch which way the drawer moves.", answer: "It is a pull, because the drawer comes toward you." }],
        quiz: [
          { id: "c1-pull-q1", question: "A pull brings an object…", choices: ["toward you", "only sideways", "away from you", "into the sky"], answerIndex: 0, explanation: "A pull moves the object toward you." },
        ],
      },
    ],
  },
  {
    id: "c1-light",
    grade: 1,
    title: "Light and shadows",
    promise: "Light lets us see, and blocked light makes a shadow.",
    scopeNote: "Class 1 ideas about light. Straight-line rays come later.",
    topics: [
      {
        id: "c1-shadow",
        title: "Shadows",
        aliases: ["shadow", "light", "dark shape"],
        idea: "A shadow appears when something blocks light.",
        younger: "You need light to make a shadow. Your body can block sunlight, and a dark shape falls on the ground. No light means no shadow.",
        example: "On a sunny day your shadow follows you across the playground.",
        formulaIds: [],
        mistake: { wrong: "Shadows can be made in a completely dark room.", right: "A shadow needs light and something to block that light." },
        check: { question: "Can you make a shadow with no light at all?", answer: "No." },
        keyPoints: ["Shadows need light.", "The object blocks the light.", "A dark room has no shadows because there is no light."],
        sketch: "shadow",
        practice: [{ id: "c1-shadow-p1", question: "What two things do you need to make a shadow?", hint: "Think of the Sun and your body.", answer: "Light, and an object that blocks it." }],
        quiz: [
          { id: "c1-shadow-q1", question: "A shadow is made when an object…", choices: ["blocks light", "makes a sound", "becomes cold", "starts to float"], answerIndex: 0, explanation: "The object stops some light, and the dark patch is the shadow." },
        ],
      },
      {
        id: "c1-see",
        title: "We see with light",
        aliases: ["see", "eyes", "dark"],
        idea: "We need light to see things.",
        younger: "In a bright room you can see toys and faces. In the dark, your eyes do not have light to use, so things are hard to see.",
        example: "A torch helps you see under the bed.",
        formulaIds: [],
        mistake: { wrong: "Eyes can see just as well in total darkness.", right: "Eyes need some light." },
        check: { question: "Why is a torch useful at night?", answer: "It gives light so you can see." },
        keyPoints: ["Light helps us see.", "Darkness makes seeing hard.", "The Sun, lamps, and torches are light sources."],
        practice: [{ id: "c1-see-p1", question: "Name two things that give light.", hint: "One is in the sky.", answer: "The Sun and a lamp, or a torch and a candle." }],
        quiz: [
          { id: "c1-see-q1", question: "We see objects best when there is…", choices: ["light", "no light", "only sound", "only wind"], answerIndex: 0, explanation: "Sight needs light." },
        ],
      },
    ],
  },
  {
    id: "c1-sound-heat",
    grade: 1,
    title: "Sounds, hot, and cold",
    promise: "Sounds reach our ears. Some things are hot and some are cold.",
    scopeNote: "Safe Class 1 observations. Do not touch hot objects.",
    topics: [
      {
        id: "c1-sound",
        title: "Loud and soft sounds",
        aliases: ["sound", "loud", "soft", "noise"],
        idea: "Sounds can be loud or soft. We hear them with our ears.",
        younger: "A drum can be loud. A whisper is soft. The sound is made when something shakes, like a drum skin.",
        example: "Tapping a table makes a small sound. Banging it makes a louder one.",
        formulaIds: [],
        mistake: { wrong: "A whisper is always easier to hear than a drum.", right: "A loud sound is usually easier to hear." },
        check: { question: "Which is usually louder, a whisper or a drum?", answer: "A drum." },
        keyPoints: ["We hear with our ears.", "Sounds can be loud or soft.", "Many sounds start when something shakes."],
        sketch: "wave",
        practice: [{ id: "c1-sound-p1", question: "Name a loud sound and a soft sound in your classroom.", hint: "Think of a bell and a whisper.", answer: "A bell is loud. A whisper is soft." }],
        quiz: [
          { id: "c1-sound-q1", question: "We hear sounds with our…", choices: ["ears", "knees", "shadows", "teeth"], answerIndex: 0, explanation: "Ears are for hearing." },
        ],
      },
      {
        id: "c1-hot",
        title: "Hot and cold",
        aliases: ["hot", "cold", "warm", "temperature"],
        idea: "Some objects are hot and some are cold. Hot things can burn, so we do not touch them.",
        younger: "Ice feels cold. A flame is hot. The Sun can warm your skin. Never touch a hot pan.",
        example: "Soup that has just been cooked is hot. Ice cream is cold.",
        formulaIds: [],
        mistake: { wrong: "Metal is always cold, even in hot soup.", right: "A metal spoon left in hot soup becomes hot." },
        check: { question: "Should you touch a pan on a burning stove?", answer: "No. It can burn you." },
        keyPoints: ["Hot and cold are different.", "The Sun and flames are hot.", "Ice is cold.", "Do not touch hot pans."],
        sketch: "heat",
        practice: [{ id: "c1-hot-p1", question: "Is ice hot or cold?", hint: "Think of how it feels in your hand.", answer: "Ice is cold." }],
        quiz: [
          { id: "c1-hot-q1", question: "Which one is hot and unsafe to touch?", choices: ["a pan on the stove", "an ice cube", "a cotton ball", "a pencil"], answerIndex: 0, explanation: "A pan on the stove can burn skin." },
        ],
      },
    ],
  },
  {
    id: "c2-motion",
    grade: 2,
    title: "Moving and still",
    promise: "Some things move and some stay still. Fast and slow are different.",
    scopeNote: "Class 2 motion, before speed formulas.",
    topics: [
      {
        id: "c2-still",
        title: "Still and moving",
        aliases: ["motion", "moving", "rest", "still"],
        idea: "A moving object changes its place. A still object stays where it is.",
        younger: "A parked bicycle is still. A rolling ball is moving. If you watch the ball, you see it change place.",
        example: "Children running in a race are moving. The finish flag can stay still.",
        formulaIds: [],
        mistake: { wrong: "A sleeping cat is moving because it is alive.", right: "If it stays in the same place, it is still." },
        check: { question: "Is a book lying on a desk moving or still?", answer: "Still." },
        keyPoints: ["Moving objects change place.", "Still objects stay in place.", "You can start or stop a motion with a push or a pull."],
        sketch: "motion",
        practice: [{ id: "c2-still-p1", question: "Name one moving thing and one still thing in the room.", hint: "Look at a fan and a wall.", answer: "A spinning fan is moving. A wall is still." }],
        quiz: [
          { id: "c2-still-q1", question: "An object is moving when it…", choices: ["changes its place", "is very heavy", "is a living thing", "has a colour"], answerIndex: 0, explanation: "Motion means a change of place." },
        ],
      },
      {
        id: "c2-fast",
        title: "Fast, slow, and which way",
        aliases: ["velocity", "speed", "fast", "slow", "direction"],
        idea: "Fast and slow tell how quickly something moves. The way it goes also matters.",
        younger: "Velocity is a big word for how fast something moves and which way it goes. Speed is only how fast. Two balls can be equally fast and still go different ways.",
        example: "A ball rolling toward you and a ball rolling away can be just as fast, but they are not doing the same thing.",
        formulaIds: [],
        mistake: { wrong: "The faster child is always the one who ran farther, even if we do not know the time.", right: "Fast means more distance in the same time, or the same distance in less time." },
        check: { question: "Two children run to the same tree. One arrives first. Who was faster?", answer: "The child who arrived first." },
        keyPoints: ["Fast and slow compare motion.", "The same speed can point different ways.", "In Class 2 we say this in words, without a formula."],
        sketch: "motion",
        practice: [{ id: "c2-fast-p1", question: "If two toys travel the same path and one finishes first, which was faster?", hint: "Less time means faster for the same path.", answer: "The toy that finishes first was faster." }],
        quiz: [
          { id: "c2-fast-q1", question: "Speed tells us…", choices: ["how fast", "only the colour", "only the weight", "the name of the object"], answerIndex: 0, explanation: "Speed is about how fast the object moves." },
          { id: "c2-fast-q2", question: "For Class 2, velocity means…", choices: ["how fast and which way", "only how heavy", "only how hot", "a kind of shadow"], answerIndex: 0, explanation: "Velocity keeps the direction as well as how fast." },
        ],
      },
    ],
  },
  {
    id: "c2-float",
    grade: 2,
    title: "Light, float, and sink",
    promise: "Light and dark are different. Some things float and some sink.",
    scopeNote: "Observations only. Density comes in later classes.",
    topics: [
      {
        id: "c2-light",
        title: "Light and dark",
        aliases: ["light", "dark", "bright"],
        idea: "A place with light is bright. A place without light is dark.",
        younger: "Daytime is bright because of the Sun. A closed cupboard can be dark. Switching on a lamp makes a dark room bright.",
        example: "Your bedroom is dark at night until you turn on the light.",
        formulaIds: [],
        mistake: { wrong: "The Moon must be a hot flame because we can see it.", right: "We can see the Moon because it reflects sunlight. It is not a flame." },
        check: { question: "What can you switch on to make a dark room bright?", answer: "A lamp or a light." },
        keyPoints: ["Bright places have light.", "Dark places have little or no light.", "Lamps and the Sun are sources of light."],
        practice: [{ id: "c2-light-p1", question: "Is a closed box usually bright or dark inside?", hint: "Does light get in?", answer: "It is usually dark, because light cannot get in easily." }],
        quiz: [
          { id: "c2-light-q1", question: "A lamp makes a room…", choices: ["brighter", "heavier", "colder always", "silent"], answerIndex: 0, explanation: "A lamp adds light." },
        ],
      },
      {
        id: "c2-float",
        title: "Float and sink",
        aliases: ["float", "sink", "water"],
        idea: "Some objects stay on top of water. Others go down.",
        younger: "A leaf can float. A stone usually sinks. Floating means it stays up. Sinking means it goes down through the water.",
        example: "An empty plastic bottle floats in a bucket. A marble sinks.",
        formulaIds: [],
        mistake: { wrong: "Everything heavy sinks and everything light floats.", right: "A big ship is heavy and can still float. Shape and what it is made of matter." },
        check: { question: "Does a stone usually float or sink in a bucket of water?", answer: "It usually sinks." },
        keyPoints: ["Floating objects stay up in water.", "Sinking objects go down.", "A heavy ship can still float."],
        sketch: "float",
        practice: [{ id: "c2-float-p1", question: "Will an empty plastic bottle usually float or sink?", hint: "Try to picture it in a bucket.", answer: "It usually floats." }],
        quiz: [
          { id: "c2-float-q1", question: "A stone dropped in water usually…", choices: ["sinks", "floats forever", "becomes a shadow", "makes no change"], answerIndex: 0, explanation: "A typical stone sinks." },
        ],
      },
    ],
  },
  {
    id: "c2-sound",
    grade: 2,
    title: "Sounds near and far",
    promise: "The same sound can seem louder when you are close.",
    scopeNote: "Class 2 hearing. Speed of sound is for later classes.",
    topics: [
      {
        id: "c2-near",
        title: "Near and far sounds",
        aliases: ["near", "far", "loudness", "distance sound"],
        idea: "A sound usually seems louder when you are closer to it.",
        younger: "A bell beside your ear seems louder than the same bell across the playground. Moving closer can make a soft sound easier to hear.",
        example: "You hear a bus more clearly when it comes near your gate.",
        formulaIds: [],
        mistake: { wrong: "Every far sound is louder than every near sound.", right: "Distance matters, and so does how strong the sound was at the start." },
        check: { question: "If you walk away from a ringing bell, does it usually seem louder or softer?", answer: "Softer." },
        keyPoints: ["Closer often means louder.", "Farther often means softer.", "A very loud source can still be heard from far away."],
        practice: [{ id: "c2-near-p1", question: "Why is a whisper hard to hear from across a hall?", hint: "Think about soft and far.", answer: "A whisper is soft, and you are far from it." }],
        quiz: [
          { id: "c2-near-q1", question: "The same bell usually seems louder when you are…", choices: ["closer to it", "asleep", "under water with no bell", "farther from it"], answerIndex: 0, explanation: "Moving closer usually makes the bell seem louder." },
        ],
      },
      {
        id: "c2-shake",
        title: "Shaking makes sound",
        aliases: ["vibration", "shake", "drum"],
        idea: "Many sounds start when an object shakes back and forth.",
        younger: "That shaking is called a vibration. A guitar string shakes and you hear a note. When the shaking stops, the sound fades.",
        example: "Put your hand lightly on a ringing bell and you can feel it shake.",
        formulaIds: [],
        mistake: { wrong: "Sound can start from an object that is perfectly still.", right: "The object, or the air it disturbs, has to vibrate." },
        check: { question: "What is the shaking of a drum skin called?", answer: "A vibration." },
        keyPoints: ["Vibrations make sound.", "A still string does not keep making its note.", "You can sometimes feel the shaking."],
        practice: [{ id: "c2-shake-p1", question: "What happens to the sound when a string stops shaking?", hint: "Listen as the note dies.", answer: "The sound fades away." }],
        quiz: [
          { id: "c2-shake-q1", question: "A vibration is…", choices: ["a back-and-forth shake", "a shadow", "a kind of ice", "a pull only"], answerIndex: 0, explanation: "Vibration means a repeated shake." },
        ],
      },
    ],
  },
  {
    id: "c3-motion",
    grade: 3,
    title: "How things move",
    promise: "Pushes and pulls can start, stop, or change a motion.",
    scopeNote: "Class 3 force and motion in everyday language.",
    topics: [
      {
        id: "c3-start",
        title: "Starting and stopping",
        aliases: ["start", "stop", "force", "push"],
        idea: "A push or a pull can start an object moving, speed it up, slow it down, or stop it.",
        younger: "A ball at rest starts moving when you kick it. You can stop a rolling ball by catching it. The kick and the catch are forces.",
        example: "A goalkeeper stops a football with their hands.",
        formulaIds: [],
        mistake: { wrong: "Moving objects stop even when nothing at all acts on them, including the ground.", right: "On a real playground, friction and air slow things down. In later classes you will separate those effects." },
        check: { question: "What can a kick do to a still football?", answer: "It can start the football moving." },
        keyPoints: ["Forces can start motion.", "Forces can stop motion.", "Forces can also change the way something is moving."],
        sketch: "push",
        practice: [{ id: "c3-start-p1", question: "Give one way to stop a swing.", hint: "You use your feet or hands.", answer: "You can drag your feet or hold the swing. That is a force." }],
        quiz: [
          { id: "c3-start-q1", question: "A force can…", choices: ["start or stop a motion", "only change colour", "only make shadows", "remove mass"], answerIndex: 0, explanation: "Forces change motion." },
        ],
      },
      {
        id: "c3-path",
        title: "Straight and curved paths",
        aliases: ["path", "straight", "curve"],
        idea: "A moving object follows a path. The path can be straight or curved.",
        younger: "A ball you roll on a smooth floor can go nearly straight. A ball on a string swung in a circle follows a curved path.",
        example: "A bicycle turning a corner follows a curve.",
        formulaIds: [],
        mistake: { wrong: "Every moving thing must travel in a straight line.", right: "Paths can bend when a force pushes the object sideways." },
        check: { question: "Is the path of a merry-go-round horse straight or curved?", answer: "Curved." },
        keyPoints: ["Motion follows a path.", "Paths can be straight or curved.", "A sideways force can bend a path."],
        practice: [{ id: "c3-path-p1", question: "Name a toy that moves in a circle.", hint: "Think of a fan or a merry-go-round.", answer: "A fan blade, or a toy on a roundabout, moves in a circle." }],
        quiz: [
          { id: "c3-path-q1", question: "A path can be…", choices: ["straight or curved", "only straight", "only invisible", "only hot"], answerIndex: 0, explanation: "Objects can move in straight lines or along curves." },
        ],
      },
    ],
  },
  {
    id: "c3-shadows",
    grade: 3,
    title: "Changing shadows",
    promise: "Shadows change when the light or the object moves.",
    scopeNote: "Class 3 shadow observations.",
    topics: [
      {
        id: "c3-long",
        title: "Long and short shadows",
        aliases: ["long shadow", "short shadow", "sun shadow"],
        idea: "A shadow grows longer or shorter when the light moves higher or lower.",
        younger: "In the morning the Sun is low and your shadow can be long. Near midday the Sun is high and the shadow is shorter.",
        example: "Your morning shadow on the way to school is often longer than your shadow at lunch.",
        formulaIds: [],
        mistake: { wrong: "Your shadow is the same length all day.", right: "It changes as the Sun’s position changes." },
        check: { question: "When the Sun is high in the sky, is your shadow usually longer or shorter?", answer: "Shorter." },
        keyPoints: ["Low light can make a long shadow.", "High light can make a short shadow.", "Moving the lamp also changes the shadow."],
        sketch: "shadow",
        practice: [{ id: "c3-long-p1", question: "What happens to a shadow if you move a torch lower?", hint: "Think of the morning Sun.", answer: "The shadow usually gets longer." }],
        quiz: [
          { id: "c3-long-q1", question: "A high Sun usually makes a shadow that is…", choices: ["shorter", "always absent", "a sound", "heavier"], answerIndex: 0, explanation: "When the light is overhead, the shadow is shorter." },
        ],
      },
      {
        id: "c3-block",
        title: "What blocks light",
        aliases: ["opaque", "transparent", "block light"],
        idea: "Opaque objects block light and can cast a dark shadow. Clear objects let most light through.",
        younger: "A book is opaque, so it makes a dark shadow. A clean glass window lets light through, so it does not make a dark shadow like the book.",
        example: "A hand in front of a torch makes a hand-shaped shadow on the wall.",
        formulaIds: [],
        mistake: { wrong: "Clear glass blocks light as fully as a wooden board.", right: "Clear glass lets most light pass." },
        check: { question: "Which casts the darker shadow, a book or a clean window pane?", answer: "The book." },
        keyPoints: ["Opaque objects block light.", "Transparent objects let light through.", "The shadow’s shape follows the object."],
        practice: [{ id: "c3-block-p1", question: "Why can you see the street through a clean window?", hint: "Does the glass block all the light?", answer: "The glass lets light through, so you can see." }],
        quiz: [
          { id: "c3-block-q1", question: "An opaque object…", choices: ["blocks light", "is always a liquid", "cannot cast a shadow", "makes sound by itself"], answerIndex: 0, explanation: "Opaque means light does not pass through." },
        ],
      },
    ],
  },
  {
    id: "c3-warm",
    grade: 3,
    title: "Sound and warmth",
    promise: "You can make sounds, and heat can warm a cold object.",
    scopeNote: "Qualitative Class 3 ideas.",
    topics: [
      {
        id: "c3-make-sound",
        title: "Making sounds",
        aliases: ["make sound", "pluck", "blow"],
        idea: "You make a sound by making something vibrate: pluck, tap, blow, or speak.",
        younger: "Plucking a rubber band makes it shake and sing. Blowing across a bottle makes the air inside shake. Your voice comes from vibrations in your throat.",
        example: "A teacher’s whistle makes a loud sound when air is blown through it.",
        formulaIds: [],
        mistake: { wrong: "Speaking does not involve any vibration.", right: "Vocal cords vibrate when you speak." },
        check: { question: "What must a rubber band do to make a twang?", answer: "It must vibrate, or shake." },
        keyPoints: ["Plucking, tapping, and blowing can make sound.", "The vibrating part might be a string, air, or your throat.", "Stopping the vibration stops the sound."],
        practice: [{ id: "c3-make-sound-p1", question: "How can you make a sound with a table?", hint: "Use your hand.", answer: "Tap it so the surface vibrates." }],
        quiz: [
          { id: "c3-make-sound-q1", question: "A plucked string makes a sound because it…", choices: ["vibrates", "becomes opaque", "loses its shadow", "stops all motion"], answerIndex: 0, explanation: "The vibration produces the sound." },
        ],
      },
      {
        id: "c3-warm",
        title: "Warm and cool objects",
        aliases: ["warm", "cool", "heat"],
        idea: "Heat can flow from a warmer object to a cooler one.",
        younger: "A hot cup warms your cold hands. The cup gets a little cooler and your hands get warmer. Heat moves from the hotter thing to the cooler thing.",
        example: "A metal spoon left in hot tea becomes warm.",
        formulaIds: [],
        mistake: { wrong: "Cold flows into the spoon and that is the only way the tea cools.", right: "In school science we say heat leaves the hotter tea and warms the spoon." },
        check: { question: "If you hold a warm cup, which way does heat move?", answer: "From the warm cup into your cooler hands." },
        keyPoints: ["Heat moves from hotter to cooler.", "A warm object can cool down while it heats something else.", "We still do not need a formula in Class 3."],
        sketch: "heat",
        practice: [{ id: "c3-warm-p1", question: "Why does a spoon in hot tea become warm?", hint: "Where does the heat come from?", answer: "Heat moves from the hot tea into the spoon." }],
        quiz: [
          { id: "c3-warm-q1", question: "Heat moves from…", choices: ["hotter to cooler", "cooler to hotter by itself", "shadow to light", "soft sound to loud sound"], answerIndex: 0, explanation: "Heat flows from the hotter object to the cooler one." },
        ],
      },
    ],
  },
  {
    id: "c4-force",
    grade: 4,
    title: "Force",
    promise: "A force is a push or a pull. Forces can work together or against each other.",
    scopeNote: "Class 4 forces, still without F = ma.",
    topics: [
      {
        id: "c4-what-force",
        title: "What a force does",
        aliases: ["force", "push", "pull"],
        idea: "A force is a push or a pull. It can change the speed or the direction of a motion.",
        younger: "Your hand, a bat, the wind, and a magnet can all exert forces. The object may speed up, slow down, or turn.",
        example: "Wind pushes a kite and can change the way it flies.",
        formulaIds: [],
        mistake: { wrong: "A force is the same thing as the speed of an object.", right: "Force is the push or pull. Speed is how fast the object is already moving." },
        check: { question: "Is a force a push, a pull, or either?", answer: "Either. A force can be a push or a pull." },
        keyPoints: ["Force means push or pull.", "Forces can change speed or direction.", "Force is not the same word as speed."],
        sketch: "push",
        practice: [{ id: "c4-what-force-p1", question: "Name a force you cannot see but can feel.", hint: "Think about a windy day.", answer: "The wind, or the pull of a magnet, or gravity." }],
        quiz: [
          { id: "c4-what-force-q1", question: "A force is…", choices: ["a push or a pull", "only a colour", "only a sound", "the name of a shadow"], answerIndex: 0, explanation: "That is the Class 4 definition." },
        ],
      },
      {
        id: "c4-two-forces",
        title: "More than one force",
        aliases: ["two forces", "tug of war", "net"],
        idea: "When two forces pull in opposite ways, the stronger one decides the motion.",
        younger: "In a tug of war, both teams pull. If the pulls are equal, the rope can stay still. If one team pulls harder, the rope moves their way.",
        example: "Two children push a box from opposite sides. The stronger push wins.",
        formulaIds: [],
        mistake: { wrong: "The larger child always applies the larger force.", right: "The size of the person does not tell you the force. You have to know how hard they push." },
        check: { question: "Two equal opposite pulls act on a rope. What can the rope do?", answer: "It can stay still." },
        keyPoints: ["More than one force can act at once.", "Equal opposite forces can cancel.", "The stronger unbalanced force sets the direction."],
        practice: [{ id: "c4-two-forces-p1", question: "Why might a box not move if two children push it from opposite sides?", hint: "Compare the two pushes.", answer: "The pushes can be equal and opposite, so they balance." }],
        quiz: [
          { id: "c4-two-forces-q1", question: "Equal opposite forces on a still rope can…", choices: ["leave it still", "always break it", "remove gravity", "make a shadow"], answerIndex: 0, explanation: "Balanced forces do not start the motion." },
        ],
      },
    ],
  },
  {
    id: "c4-friction",
    grade: 4,
    title: "Friction you can feel",
    promise: "Friction is the force that opposes sliding.",
    scopeNote: "No coefficient of friction yet. That formula is for later classes.",
    topics: [
      {
        id: "c4-rough",
        title: "Rough and smooth",
        aliases: ["friction", "rough", "smooth", "slide"],
        idea: "Friction opposes sliding. Rough surfaces usually make more friction than smooth ones.",
        younger: "Your shoes grip the ground because of friction. On ice, the grip is small, so you slip. Rubbing your hands makes them warm because of friction.",
        example: "A ball rolls farther on a smooth floor than on a thick carpet.",
        formulaIds: [],
        mistake: { wrong: "Friction always makes motion impossible.", right: "Friction opposes sliding. It can slow a motion, and it also lets us walk." },
        check: { question: "Why are you more likely to slip on ice than on a dry path?", answer: "Ice gives less friction, so your shoe cannot grip as well." },
        keyPoints: ["Friction opposes sliding.", "Rough surfaces usually grip more.", "Friction lets shoes grip the ground.", "Friction can warm rubbing surfaces."],
        practice: [{ id: "c4-rough-p1", question: "Why do shoes have rough soles?", hint: "Think about walking.", answer: "The rough sole increases friction so you do not slip." }],
        quiz: [
          { id: "c4-rough-q1", question: "Friction usually…", choices: ["opposes sliding", "removes all mass", "creates darkness", "stops light"], answerIndex: 0, explanation: "Friction acts against sliding." },
        ],
      },
      {
        id: "c4-useful",
        title: "Useful and troublesome friction",
        aliases: ["useful friction", "grip"],
        idea: "Friction is useful when we need grip, and troublesome when we want something to slide easily.",
        younger: "Brakes use friction to stop a bicycle. A rusty hinge is hard to move because friction is large. Oil can reduce that friction.",
        example: "Writing with a pencil needs a little friction between the pencil and the paper.",
        formulaIds: [],
        mistake: { wrong: "We should always try to remove all friction.", right: "Without friction, walking, writing, and braking would fail." },
        check: { question: "Do bicycle brakes use friction or try to remove it?", answer: "They use friction to slow the wheel." },
        keyPoints: ["Brakes need friction.", "Oil can reduce friction in a hinge.", "Friction can be helpful or troublesome."],
        practice: [{ id: "c4-useful-p1", question: "Give one place where you want less friction.", hint: "Think of a door hinge or a slide.", answer: "A door hinge, or a playground slide." }],
        quiz: [
          { id: "c4-useful-q1", question: "Bicycle brakes stop the bike by using…", choices: ["friction", "a shadow", "cold air only", "a mirror"], answerIndex: 0, explanation: "Brake pads rub on the wheel." },
        ],
      },
    ],
  },
  {
    id: "c4-travel",
    grade: 4,
    title: "Light and sound travel",
    promise: "Light and sound both travel, but not in the same way.",
    scopeNote: "Class 4 descriptions. Wave speed is introduced later.",
    topics: [
      {
        id: "c4-light-straight",
        title: "Light travels",
        aliases: ["light travels", "straight", "ray"],
        idea: "In Class 4 we say light travels in straight lines. That is why shadows have fairly sharp edges.",
        younger: "A torch beam goes straight until it hits something. You cannot see around a thick wall, because the light from the other side does not bend around it in ordinary life.",
        example: "Dust in a dark room shows a torch beam as a straight path.",
        formulaIds: [],
        mistake: { wrong: "Light always curves around ordinary walls like water in a hose.", right: "For school ray diagrams, light travels in straight lines until it hits a mirror or passes into another material." },
        check: { question: "Why does a shadow have a shape like the object?", answer: "Light travels in straight lines, so the blocked region copies the object’s outline." },
        keyPoints: ["Light travels.", "In this class, its path is a straight line.", "That straight path explains sharp shadows."],
        sketch: "shadow",
        practice: [{ id: "c4-light-straight-p1", question: "Why can’t you see around a corner with ordinary light?", hint: "Does the light bend around the wall?", answer: "The light travels in straight lines and the wall blocks it." }],
        quiz: [
          { id: "c4-light-straight-q1", question: "In Class 4, a light beam is drawn as…", choices: ["a straight line", "a circle only", "a sound wave", "a magnet"], answerIndex: 0, explanation: "The ray model uses straight lines." },
        ],
      },
      {
        id: "c4-sound-travel",
        title: "Sound travels",
        aliases: ["sound travels", "medium", "air"],
        idea: "Sound travels through a material such as air, water, or wood. It does not travel through empty space.",
        younger: "You hear a clap because the air carries the vibration to your ear. Sound can also travel along a desk: a tap at one end can be heard at the other.",
        example: "Thunder reaches you after the lightning flash because sound travels more slowly than light.",
        formulaIds: [],
        mistake: { wrong: "Sound travels faster than light, which is why we hear thunder first.", right: "We see the flash first. Light is much faster than sound." },
        check: { question: "Which do you notice first in a distant storm, the flash or the thunder?", answer: "The flash." },
        keyPoints: ["Sound needs a material to travel through.", "Air, water, and solids can carry sound.", "Light arrives before sound from a distant flash."],
        practice: [{ id: "c4-sound-travel-p1", question: "Why do you see fireworks before you hear the bang?", hint: "Compare light and sound.", answer: "Light travels much faster than sound." }],
        quiz: [
          { id: "c4-sound-travel-q1", question: "Sound needs…", choices: ["a material to travel through", "a mirror only", "a magnet only", "total darkness"], answerIndex: 0, explanation: "Sound does not travel through a vacuum." },
        ],
      },
    ],
  },
  {
    id: "c5-machines",
    grade: 5,
    title: "Simple machines",
    promise: "Levers and slopes help us move loads.",
    scopeNote: "Class 5 machines, described without the later torque formula.",
    topics: [
      {
        id: "c5-lever",
        title: "Levers",
        aliases: ["lever", "seesaw", "simple machine"],
        idea: "A lever is a bar that turns on a fulcrum. It can help lift a load.",
        younger: "A seesaw is a lever. The fulcrum is the pivot in the middle. Sitting farther from the pivot can balance a heavier friend who sits closer.",
        example: "A bottle opener and a crowbar are levers.",
        formulaIds: [],
        mistake: { wrong: "The fulcrum is the load you are lifting.", right: "The fulcrum is the pivot. The load is the object you want to move." },
        check: { question: "What do we call the pivot of a seesaw?", answer: "The fulcrum." },
        keyPoints: ["A lever turns on a fulcrum.", "It can make a load easier to move.", "A seesaw is a familiar lever."],
        sketch: "lever",
        practice: [{ id: "c5-lever-p1", question: "On a seesaw, where should a lighter child sit to balance a heavier child?", hint: "Closer to the pivot or farther?", answer: "Farther from the fulcrum." }],
        quiz: [
          { id: "c5-lever-q1", question: "The fulcrum of a lever is the…", choices: ["pivot", "load", "sound", "shadow"], answerIndex: 0, explanation: "The bar turns about the fulcrum." },
        ],
      },
      {
        id: "c5-slope",
        title: "Slopes",
        aliases: ["slope", "ramp", "inclined plane"],
        idea: "A slope, or inclined plane, lets you raise a load with a smaller force over a longer distance.",
        younger: "Pushing a wheelchair up a ramp is easier than lifting it straight up, but you travel farther. The work is spread out along the slope.",
        example: "A loading ramp helps people push a heavy box into a truck.",
        formulaIds: [],
        mistake: { wrong: "A ramp removes the need for any force.", right: "You still push. The push can be smaller because the distance is longer." },
        check: { question: "Why is a ramp helpful for a heavy box?", answer: "You can use a smaller force, over a longer distance." },
        keyPoints: ["A slope is a simple machine.", "The force can be smaller.", "The distance along the ramp is longer."],
        practice: [{ id: "c5-slope-p1", question: "Which takes the longer path, lifting a box straight up or pushing it up a ramp to the same height?", hint: "Look at the shape of the ramp.", answer: "Pushing it up the ramp." }],
        quiz: [
          { id: "c5-slope-q1", question: "A ramp helps because the force can be…", choices: ["smaller over a longer distance", "zero", "always downward only", "a kind of light"], answerIndex: 0, explanation: "The slope trades a longer distance for a smaller force." },
        ],
      },
    ],
  },
  {
    id: "c5-gravity",
    grade: 5,
    title: "Gravity and floating",
    promise: "Earth pulls objects down. Floating depends on more than weight alone.",
    scopeNote: "Everyday gravity. The law F = Gm1m2/r² is for senior classes.",
    topics: [
      {
        id: "c5-gravity",
        title: "Earth pulls downward",
        aliases: ["gravity", "weight", "fall"],
        idea: "Gravity is the pull of the Earth on objects. That pull is why things fall down.",
        younger: "If you drop a pencil, it falls. The Earth’s pull is called gravity. Your weight is that pull. In later classes, weight is written W = mg.",
        example: "A ball thrown upward slows, stops, and comes back down because of gravity.",
        formulaIds: [],
        mistake: { wrong: "Heavy objects always fall much faster than light ones in ordinary air.", right: "Without much air resistance, they fall together. A feather is slower mainly because of the air." },
        check: { question: "What do we call Earth’s downward pull?", answer: "Gravity." },
        keyPoints: ["Gravity pulls objects toward Earth.", "Dropped objects fall downward.", "Weight is the pull of gravity.", "Air can change how a light object falls."],
        sketch: "gravity",
        practice: [{ id: "c5-gravity-p1", question: "Why does a ball come back down after you throw it up?", hint: "Name the pull.", answer: "Gravity pulls it back toward Earth." }],
        quiz: [
          { id: "c5-gravity-q1", question: "A dropped stone falls because of…", choices: ["gravity", "friction only", "its colour", "sound"], answerIndex: 0, explanation: "Earth’s gravity pulls the stone downward." },
        ],
      },
      {
        id: "c5-float",
        title: "Why some things float",
        aliases: ["float", "sink", "boat"],
        idea: "An object floats in water when the upward push from the water can balance its weight.",
        younger: "Water pushes up on a boat. If that upward push matches the boat’s weight, the boat floats. A solid stone does not get enough upward push, so it sinks.",
        example: "A steel ship floats because its shape holds a lot of air and pushes aside a lot of water.",
        formulaIds: [],
        mistake: { wrong: "Steel always sinks, so a steel ship is impossible.", right: "A hollow steel ship can float even though a solid steel block sinks." },
        check: { question: "What upward effect helps a boat float?", answer: "The upward push of the water." },
        keyPoints: ["Water can push upward.", "Floating means that upward push balances the weight.", "Shape matters, which is why ships float."],
        sketch: "float",
        practice: [{ id: "c5-float-p1", question: "Why can a steel ship float when a steel bolt sinks?", hint: "Think about shape and the water pushed aside.", answer: "The ship pushes aside enough water for the upward push to balance its weight." }],
        quiz: [
          { id: "c5-float-q1", question: "A floating boat is balanced by…", choices: ["an upward push from the water", "its colour", "a shadow", "sound waves"], answerIndex: 0, explanation: "The water’s upward force balances the weight." },
        ],
      },
    ],
  },
  {
    id: "c5-mirrors",
    grade: 5,
    title: "Mirrors",
    promise: "A mirror sends light back so you can see an image.",
    scopeNote: "Plane mirrors only. The mirror formula is for Class 10.",
    topics: [
      {
        id: "c5-mirror",
        title: "What a mirror does",
        aliases: ["mirror", "reflection", "image"],
        idea: "A mirror reflects light. The image in a plane mirror looks the same size and appears behind the mirror.",
        younger: "When you look in a bathroom mirror, light from your face bounces off the mirror and comes back to your eyes. The image is reversed left to right.",
        example: "A plane mirror in a shop shows you an image as tall as you are.",
        formulaIds: [],
        mistake: { wrong: "A plane mirror makes you look larger.", right: "A plane mirror’s image is the same size as the object." },
        check: { question: "Does a plane bathroom mirror make your image larger, smaller, or the same size?", answer: "The same size." },
        keyPoints: ["Mirrors reflect light.", "A plane-mirror image is the same size.", "Left and right look swapped.", "The image seems to be behind the mirror."],
        sketch: "mirror",
        practice: [{ id: "c5-mirror-p1", question: "If you raise your right hand in front of a plane mirror, which hand does the image appear to raise?", hint: "The image is reversed left to right.", answer: "It appears to raise the left hand." }],
        quiz: [
          { id: "c5-mirror-q1", question: "A plane mirror’s image is…", choices: ["the same size as you", "always tiny", "always upside down for a face-on view", "a shadow"], answerIndex: 0, explanation: "Plane mirrors do not magnify." },
        ],
      },
      {
        id: "c5-shiny",
        title: "Shiny and dull surfaces",
        aliases: ["shiny", "reflect", "dull"],
        idea: "Smooth shiny surfaces reflect light in a clear way. Dull surfaces scatter it.",
        younger: "A calm lake can show a clear reflection. A rough wall scatters light, so you do not see a clear image of your face.",
        example: "You can see your face in a steel plate if it is polished, but not if it is scratched and dull.",
        formulaIds: [],
        mistake: { wrong: "Only glass can reflect light.", right: "Any smooth shiny surface, including still water or polished metal, can reflect." },
        check: { question: "Why is a reflection clearer in still water than in rippling water?", answer: "The still surface is smooth, so it reflects in a regular way." },
        keyPoints: ["Smooth surfaces give clear reflections.", "Rough surfaces scatter light.", "Water and metal can act like mirrors when they are smooth."],
        practice: [{ id: "c5-shiny-p1", question: "Name a surface, other than a glass mirror, that can show your reflection.", hint: "Think of a kitchen or a lake.", answer: "A polished steel plate, or very still water." }],
        quiz: [
          { id: "c5-shiny-q1", question: "A rough wall does not show a clear face because it…", choices: ["scatters light", "removes gravity", "stops all sound", "has no colour"], answerIndex: 0, explanation: "Scattering sends light in many directions." },
        ],
      },
    ],
  },
];
