import type { Chapter } from "../types";

export const secondaryChapters: Chapter[] = [
  {
    id: "c9-motion",
    grade: 9,
    title: "Motion",
    promise: "Distance, displacement, speed, velocity, and acceleration describe motion along a line.",
    scopeNote: "Class 9 motion with constant acceleration. The checker uses the three equations of motion.",
    topics: [
      {
        id: "c9-displacement",
        title: "Distance and displacement",
        aliases: ["distance", "displacement"],
        idea: "Distance is the length of the actual path. Displacement is the straight change in position from the start to the end, and it has a direction.",
        younger: "If you walk around a square and return to your desk, the distance is the whole walk and the displacement is zero.",
        senior: "Distance is a scalar and cannot be negative. Displacement is a vector. Its sign depends on the direction you call positive.",
        example: "A bus goes 3 km east and 4 km north. The distance is 7 km. The displacement magnitude is 5 km.",
        formulaIds: [],
        mistake: { wrong: "Distance and displacement are always equal.", right: "They are equal only for motion in one direction along a straight line." },
        check: { question: "An athlete runs one full lap and stops where they started. What is the displacement?", answer: "Zero." },
        keyPoints: ["Distance is the path length.", "Displacement is the straight change of position.", "Displacement can be zero when distance is not.", "Distance is never negative."],
        table: {
          caption: "Do not swap these",
          headers: ["", "Distance", "Displacement"],
          rows: [
            ["Kind", "Scalar", "Vector"],
            ["Path", "Actual path", "Straight from start to end"],
            ["Full lap", "The lap length", "Zero"],
          ],
        },
        practice: [{ id: "c9-displacement-p1", question: "You walk 6 m east and then 6 m west. What are the distance and the displacement?", hint: "Add the path. Then look at the start and end.", answer: "Distance is 12 m. Displacement is zero." }],
        quiz: [
          { id: "c9-displacement-q1", question: "After one full circle back to the start, displacement is…", choices: ["zero", "equal to the circumference", "always negative", "equal to the speed"], answerIndex: 0, explanation: "The start and end are the same point." },
          { id: "c9-displacement-q2", question: "Distance is…", choices: ["the length of the path", "always a vector", "the same as velocity", "measured in newtons"], answerIndex: 0, explanation: "Distance measures how much path was covered." },
        ],
      },
      {
        id: "c9-velocity",
        title: "Speed and velocity",
        aliases: ["velocity", "speed", "average velocity"],
        idea: "Speed is distance divided by time and has no direction. Average velocity is displacement divided by time and has a direction.",
        younger: "A car going north at 40 km/h and a car going south at 40 km/h have the same speed but opposite velocities.",
        senior: "Average speed is total distance over total time. Average velocity is total displacement over total time. On a closed path the average velocity is zero even when the average speed is not.",
        example: "A cyclist rides 300 m east in 60 s. The average velocity is 5 m/s east.",
        formulaIds: ["speed", "velocity", "average-speed"],
        mistake: { wrong: "Average velocity uses the path length.", right: "Average velocity uses displacement. Using the path gives average speed." },
        check: { question: "A runner goes 100 m north in 20 s. What is the average velocity?", answer: "5 m/s north." },
        keyPoints: ["Speed has no direction.", "Velocity has direction.", "Average velocity = displacement / time.", "Average speed = total distance / total time."],
        sketch: "motion",
        table: {
          headers: ["", "Average speed", "Average velocity"],
          rows: [
            ["Uses", "Total distance", "Displacement"],
            ["Direction", "None", "Required"],
            ["Closed loop", "Not zero", "Zero"],
          ],
        },
        worked: {
          prompt: "A cyclist rides 300 m east in 60 s. What is the average velocity?",
          formulaId: "velocity",
          known: { s: { value: 300, unit: "m" }, t: { value: 60, unit: "s" } },
          find: "v",
          after: "The magnitude is 5 m/s. The direction is east, so the velocity is 5 m/s east.",
        },
        practice: [
          {
            id: "c9-velocity-p1",
            question: "A bus covers 100 m east in 20 s along a straight road. Find the average velocity.",
            hint: "Displacement and distance match on this straight one-way trip.",
            answer: "5 m/s east.",
            worked: { formulaId: "velocity", known: { s: { value: 100, unit: "m" }, t: { value: 20, unit: "s" } }, find: "v" },
          },
        ],
        quiz: [
          { id: "c9-velocity-q1", question: "Velocity differs from speed because velocity…", choices: ["has direction", "is always larger", "has no unit", "uses mass"], answerIndex: 0, explanation: "Velocity is a vector." },
          { id: "c9-velocity-q2", question: "Average velocity uses…", choices: ["displacement and time", "distance only", "mass and force", "area and pressure"], answerIndex: 0, explanation: "Displacement over time, with a direction." },
        ],
      },
      {
        id: "c9-acceleration",
        title: "Acceleration",
        aliases: ["acceleration", "retardation", "deceleration"],
        idea: "Acceleration is the change in velocity divided by the time taken. Slowing down is acceleration opposite to the velocity.",
        younger: "If a bike starts from rest and reaches 10 m/s in 5 s, its acceleration is 2 m/s², as long as the change is steady.",
        senior: "Acceleration is a vector. A negative sign means the acceleration points opposite the direction you chose as positive. It does not automatically mean the object is moving backward.",
        example: "A car speeding up on a straight road has acceleration in the direction of its velocity.",
        formulaIds: ["acceleration", "v-uat"],
        mistake: { wrong: "A negative acceleration always means the object is moving backward.", right: "The sign depends on your chosen positive direction. Slowing while moving forward is negative acceleration if forward is positive." },
        check: { question: "A body goes from 0 to 10 m/s in 5 s at a steady rate. What is the acceleration?", answer: "2 m/s²." },
        keyPoints: ["a = (v − u) / t.", "The SI unit is m/s².", "Speeding up and slowing down are both acceleration.", "The sign follows the chosen direction."],
        worked: {
          prompt: "A scooter starts from rest and reaches 10 m/s in 5 s. Find the acceleration.",
          formulaId: "acceleration",
          known: { u: { value: 0, unit: "m/s" }, v: { value: 10, unit: "m/s" }, t: { value: 5, unit: "s" } },
          find: "a",
        },
        practice: [{ id: "c9-acceleration-p1", question: "A car slows from 20 m/s to 8 m/s in 4 s. Find the acceleration if forward is positive.", hint: "a = (v − u) / t.", answer: "−3 m/s².", worked: { formulaId: "acceleration", known: { u: { value: 20, unit: "m/s" }, v: { value: 8, unit: "m/s" }, t: { value: 4, unit: "s" } }, find: "a" } }],
        quiz: [
          { id: "c9-acceleration-q1", question: "The SI unit of acceleration is…", choices: ["m/s²", "m/s", "N", "kg"], answerIndex: 0, explanation: "Velocity per time is m/s²." },
        ],
      },
      {
        id: "c9-equations",
        title: "Equations of motion",
        aliases: ["equations of motion", "v = u + at", "uniform acceleration"],
        idea: "When acceleration is constant, v = u + at, s = ut + ½at², and v² = u² + 2as.",
        younger: "These three equations are only for constant acceleration along a straight line. “From rest” means u = 0.",
        senior: "They are not valid for changing acceleration. v² = u² + 2as gives a speed, so the checker reports the non-negative square root. Direction still has to be decided from the problem.",
        example: "From rest, a = 2 m/s² and t = 5 s give v = 10 m/s.",
        formulaIds: ["v-uat", "s-uat", "v2-uas"],
        mistake: { wrong: "These equations can be used when the acceleration keeps changing.", right: "The acceleration must be constant." },
        check: { question: "A body starts from rest with a = 2 m/s². What is v after 5 s?", answer: "10 m/s." },
        keyPoints: ["Use them only for constant acceleration.", "u = 0 when the body starts from rest.", "Choose the equation that contains the quantities you know.", "If v² would be negative, the values are impossible."],
        worked: {
          prompt: "A body starts from rest and accelerates at 2 m/s² for 5 s. Find the final velocity.",
          formulaId: "v-uat",
          known: { u: { value: 0, unit: "m/s" }, a: { value: 2, unit: "m/s²" }, t: { value: 5, unit: "s" } },
          find: "v",
        },
        practice: [{ id: "c9-equations-p1", question: "From rest, a = 2 m/s² for 5 s. How far does the body go?", hint: "Use s = ut + ½at² with u = 0.", answer: "25 m.", worked: { formulaId: "s-uat", known: { u: { value: 0, unit: "m/s" }, a: { value: 2, unit: "m/s²" }, t: { value: 5, unit: "s" } }, find: "s" } }],
        quiz: [
          { id: "c9-equations-q1", question: "v = u + at requires acceleration to be…", choices: ["constant", "zero", "changing every second", "equal to mass"], answerIndex: 0, explanation: "The equation is derived for constant acceleration." },
          { id: "c9-equations-q2", question: "“Starts from rest” means…", choices: ["u = 0", "a = 0", "v is infinite", "s is zero at every time"], answerIndex: 0, explanation: "The initial velocity is zero." },
        ],
      },
    ],
  },
  {
    id: "c9-laws",
    grade: 9,
    title: "Force and laws of motion",
    promise: "Newton’s laws connect force, mass, and acceleration.",
    scopeNote: "Class 9. F = ma uses the net force. Action and reaction act on different bodies.",
    topics: [
      {
        id: "c9-newton",
        title: "Newton’s laws",
        aliases: ["newton", "inertia", "action reaction", "f = ma", "force"],
        idea: "A body stays at rest or in uniform motion unless a net force acts. The net force equals mass times acceleration. Action and reaction are equal, opposite, and on different bodies.",
        younger: "Inertia is the tendency to keep the present motion. A heavier body needs a larger net force for the same acceleration.",
        senior: "F and a are vectors in the same direction. The third-law pair never cancels on one free-body diagram, because the two forces act on two different objects.",
        example: "A 3 kg box with a net force of 12 N accelerates at 4 m/s².",
        formulaIds: ["newton-second", "momentum"],
        mistake: { wrong: "The action and reaction on the same object cancel, so nothing can ever accelerate.", right: "They act on different objects. The net force on one object can still be nonzero." },
        check: { question: "A 2 kg body has a net force of 8 N. What is its acceleration?", answer: "4 m/s²." },
        keyPoints: ["Net force changes motion.", "F = ma.", "Mass resists acceleration.", "Action and reaction act on different bodies.", "Momentum p = mv."],
        worked: {
          prompt: "A 3 kg box accelerates at 4 m/s². Find the net force.",
          formulaId: "newton-second",
          known: { m: { value: 3, unit: "kg" }, a: { value: 4, unit: "m/s²" } },
          find: "F",
        },
        practice: [{ id: "c9-newton-p1", question: "Find the momentum of a 2 kg ball moving at 3 m/s.", hint: "p = mv.", answer: "6 kg m/s.", worked: { formulaId: "momentum", known: { m: { value: 2, unit: "kg" }, v: { value: 3, unit: "m/s" } }, find: "p" } }],
        quiz: [
          { id: "c9-newton-q1", question: "Action and reaction act on…", choices: ["different bodies", "the same body and cancel there", "only liquids", "only magnets"], answerIndex: 0, explanation: "That is why they do not cancel on one object." },
          { id: "c9-newton-q2", question: "F = ma. If m = 5 kg and a = 2 m/s², F is…", choices: ["10 N", "2.5 N", "7 N", "3 N"], answerIndex: 0, explanation: "5 × 2 = 10 N." },
        ],
      },
      {
        id: "c9-momentum",
        title: "Momentum",
        aliases: ["momentum", "inertia of motion"],
        idea: "Momentum is mass times velocity. A harder-to-stop object has more momentum.",
        younger: "A slow heavy truck can have more momentum than a fast light ball. Momentum points the same way as the velocity.",
        example: "A 1000 kg car at 10 m/s has a momentum of 10000 kg m/s.",
        formulaIds: ["momentum", "impulse"],
        mistake: { wrong: "The lighter object always has less momentum.", right: "Compare mv, not mass alone." },
        check: { question: "What is the momentum of a 4 kg object moving at 5 m/s?", answer: "20 kg m/s." },
        keyPoints: ["p = mv.", "Momentum has direction.", "A large force for a short time changes momentum.", "Heavier and faster both raise momentum."],
        practice: [{ id: "c9-momentum-p1", question: "Which has more momentum: 2 kg at 10 m/s, or 5 kg at 3 m/s?", hint: "Calculate mv for each.", answer: "2 × 10 = 20, and 5 × 3 = 15, so the 2 kg object has more momentum." }],
        quiz: [
          { id: "c9-momentum-q1", question: "Momentum is…", choices: ["mass × velocity", "mass / velocity", "force × area", "distance / time"], answerIndex: 0, explanation: "p = mv." },
        ],
      },
    ],
  },
  {
    id: "c9-gravity",
    grade: 9,
    title: "Gravitation",
    promise: "Every mass attracts every other mass. Weight is the Earth’s pull.",
    scopeNote: "Class 9 gravitation. g near Earth is about 9.8 m/s² unless the question says to use 10.",
    topics: [
      {
        id: "c9-weight",
        title: "Mass and weight",
        aliases: ["weight", "mass", "gravity", "g"],
        idea: "Mass is the amount of matter, in kilograms. Weight is the gravitational force, W = mg. Near Earth’s surface, g is about 9.8 m/s².",
        younger: "Your mass stays the same on the Moon. Your weight is smaller there because g is smaller. A spring balance reads weight. A beam balance compares masses.",
        senior: "Weight is a force, so its unit is the newton. Do not write weight in kilograms. If a question says take g = 10 m/s², use 10, not 9.8.",
        example: "A 2 kg book has a weight of about 19.6 N on Earth if g = 9.8 m/s².",
        formulaIds: ["weight", "gravitation"],
        mistake: { wrong: "Mass and weight are the same and both are measured in kilograms.", right: "Mass is in kilograms. Weight is a force in newtons." },
        check: { question: "What is the weight of a 5 kg bag if g = 9.8 m/s²?", answer: "49 N." },
        keyPoints: ["Mass does not change from place to place.", "Weight = mg.", "Weight is in newtons.", "Use the g the question gives."],
        sketch: "gravity",
        worked: {
          prompt: "Find the weight of a 2 kg book. Take g = 9.8 m/s².",
          formulaId: "weight",
          known: { m: { value: 2, unit: "kg" }, g: { value: 9.8, unit: "m/s²" } },
          find: "W",
        },
        practice: [{ id: "c9-weight-p1", question: "A bag has mass 10 kg. Find its weight using g = 9.8 m/s².", hint: "Multiply mass by g.", answer: "98 N.", worked: { formulaId: "weight", known: { m: { value: 10, unit: "kg" }, g: { value: 9.8, unit: "m/s²" } }, find: "W" } }],
        quiz: [
          { id: "c9-weight-q1", question: "Weight is measured in…", choices: ["newtons", "kilograms", "metres", "seconds"], answerIndex: 0, explanation: "Weight is a force." },
          { id: "c9-weight-q2", question: "On the Moon, an astronaut’s mass…", choices: ["stays the same", "becomes zero", "is measured in newtons", "doubles because g is smaller"], answerIndex: 0, explanation: "Mass is the amount of matter. Weight changes." },
        ],
      },
      {
        id: "c9-freefall",
        title: "Free fall",
        aliases: ["free fall", "g", "falling"],
        idea: "An object falling under gravity alone has acceleration g downward. Air resistance is ignored in the basic problems.",
        younger: "From rest, the speed after time t is v = gt if downward is positive. A heavier object does not have a larger g.",
        example: "Dropped from rest for 2 s with g = 9.8 m/s², the speed is 19.6 m/s downward.",
        formulaIds: ["v-uat", "weight"],
        mistake: { wrong: "Heavier objects have a larger acceleration due to gravity.", right: "g is the same for both if air resistance is ignored." },
        check: { question: "A stone is dropped from rest. What is u?", answer: "0." },
        keyPoints: ["Free fall acceleration is g.", "Heavier does not mean larger g.", "Choose a sign for upward or downward and keep it.", "Air resistance is ignored in the basic model."],
        practice: [{ id: "c9-freefall-p1", question: "A stone is dropped from rest. Take g = 9.8 m/s² downward. Find its speed after 2 s.", hint: "v = u + gt with u = 0.", answer: "19.6 m/s downward.", worked: { formulaId: "v-uat", known: { u: { value: 0, unit: "m/s" }, a: { value: 9.8, unit: "m/s²" }, t: { value: 2, unit: "s" } }, find: "v" } }],
        quiz: [
          { id: "c9-freefall-q1", question: "Ignoring air, two different masses dropped together have…", choices: ["the same acceleration", "accelerations proportional to their masses", "no weight", "zero displacement"], answerIndex: 0, explanation: "g does not depend on the mass of the falling object." },
        ],
      },
    ],
  },
  {
    id: "c9-energy",
    grade: 9,
    title: "Work and energy",
    promise: "Work, kinetic energy, potential energy, and power have definite formulas.",
    scopeNote: "Class 9 mechanical energy. Work can be negative when the force opposes the displacement.",
    topics: [
      {
        id: "c9-work",
        title: "Work",
        aliases: ["work", "joule"],
        idea: "Work is force times displacement in the direction of the force. If the force is perpendicular to the displacement, the work is zero.",
        younger: "Holding a heavy bag still means you feel tired, but the scientific work by your upward force is zero because the bag does not move.",
        senior: "W = Fs cosθ. θ is the angle between force and displacement. Work is a scalar and can be negative.",
        example: "A 10 N force pushes a box 2 m in the same direction. The work is 20 J.",
        formulaIds: ["work"],
        mistake: { wrong: "Any effort, even with no movement, counts as scientific work.", right: "If displacement is zero, work by that force is zero." },
        check: { question: "A force of 5 N moves an object 3 m in the same direction. How much work is done?", answer: "15 J." },
        keyPoints: ["Work needs force and displacement.", "No displacement means zero work.", "The unit is the joule.", "A perpendicular force does no work."],
        worked: {
          prompt: "A force of 10 N moves a box 2 m in the same direction. Find the work.",
          formulaId: "work",
          known: { F: { value: 10, unit: "N" }, s: { value: 2, unit: "m" }, theta: { value: 0, unit: "degree" } },
          find: "W",
        },
        practice: [{ id: "c9-work-p1", question: "You hold a bag still for a minute. How much work does your upward force do on the bag?", hint: "Does the bag move?", answer: "Zero, because the displacement is zero." }],
        quiz: [
          { id: "c9-work-q1", question: "Work is zero when displacement is…", choices: ["zero", "very large", "upward", "measured in kilograms"], answerIndex: 0, explanation: "W = Fs cosθ, so s = 0 gives W = 0." },
        ],
      },
      {
        id: "c9-energy",
        title: "Kinetic and potential energy",
        aliases: ["kinetic energy", "potential energy", "energy"],
        idea: "Kinetic energy is energy of motion, ½mv². Near Earth, the change in gravitational potential energy is mgh.",
        younger: "A faster ball has more kinetic energy, and the speed is squared, so doubling the speed multiplies the kinetic energy by four. Lifting a book stores potential energy.",
        senior: "mgh is the change when the zero is chosen nearby and g is treated as constant. It is not the full −GMm/r expression.",
        example: "A 2 kg ball at 3 m/s has kinetic energy 9 J.",
        formulaIds: ["kinetic-energy", "potential-energy"],
        mistake: { wrong: "Doubling the speed doubles the kinetic energy.", right: "Kinetic energy depends on speed squared, so it becomes four times as large." },
        check: { question: "What is the kinetic energy of a 2 kg mass moving at 4 m/s?", answer: "16 J." },
        keyPoints: ["K = ½mv².", "K is never negative.", "U = mgh near Earth.", "Use the g given in the question."],
        worked: {
          prompt: "Find the kinetic energy of a 2 kg ball moving at 3 m/s.",
          formulaId: "kinetic-energy",
          known: { m: { value: 2, unit: "kg" }, v: { value: 3, unit: "m/s" } },
          find: "K",
        },
        practice: [{ id: "c9-energy-p1", question: "A 2 kg book is raised by 5 m. Find the gain in potential energy. Take g = 10 m/s².", hint: "U = mgh.", answer: "100 J.", worked: { formulaId: "potential-energy", known: { m: { value: 2, unit: "kg" }, g: { value: 10, unit: "m/s²" }, h: { value: 5, unit: "m" } }, find: "U" } }],
        quiz: [
          { id: "c9-energy-q1", question: "If speed doubles, kinetic energy becomes…", choices: ["4 times", "2 times", "the same", "half"], answerIndex: 0, explanation: "The square of 2 is 4." },
          { id: "c9-energy-q2", question: "The unit of energy is the…", choices: ["joule", "newton", "pascal", "hertz"], answerIndex: 0, explanation: "Both work and energy are in joules." },
        ],
      },
    ],
  },
  {
    id: "c9-sound",
    grade: 9,
    title: "Sound",
    promise: "Sound is a longitudinal wave and needs a medium.",
    scopeNote: "Class 9 sound, including echoes.",
    topics: [
      {
        id: "c9-wave",
        title: "Sound waves",
        aliases: ["sound wave", "longitudinal", "wavelength", "frequency"],
        idea: "Sound in air is a longitudinal wave. Its speed is frequency times wavelength. Loudness follows amplitude and pitch follows frequency.",
        younger: "The particles of air shake along the direction the sound travels. They do not travel all the way to your ear with the wave.",
        example: "A 256 Hz sound of wavelength 1.3 m has a speed of about 333 m/s.",
        formulaIds: ["wave-speed"],
        mistake: { wrong: "Air travels from the speaker to your ear along with the sound.", right: "The wave travels. The air particles oscillate about their places." },
        check: { question: "What is the wave speed if f = 200 Hz and λ = 1.7 m?", answer: "340 m/s." },
        keyPoints: ["Sound needs a medium.", "In air it is longitudinal.", "v = fλ.", "Pitch follows frequency.", "Loudness follows amplitude."],
        sketch: "wave",
        practice: [{ id: "c9-wave-p1", question: "The speed of sound is 340 m/s and the frequency is 680 Hz. Find the wavelength.", hint: "λ = v / f.", answer: "0.5 m.", worked: { formulaId: "wave-speed", known: { v: { value: 340, unit: "m/s" }, f: { value: 680, unit: "Hz" } }, find: "lambda" } }],
        quiz: [
          { id: "c9-wave-q1", question: "v = fλ connects…", choices: ["speed, frequency, and wavelength", "mass, force, and area", "voltage and resistance only", "work and time only"], answerIndex: 0, explanation: "Wave speed equals frequency times wavelength." },
        ],
      },
      {
        id: "c9-echo",
        title: "Echoes",
        aliases: ["echo", "reflection of sound"],
        idea: "An echo is reflected sound. The sound goes to the reflector and back, so the one-way distance is vt/2.",
        younger: "If you hear the echo 2 s later and sound travels at 340 m/s, the wall is 340 m away, not 680 m.",
        example: "Clapping near a cliff and hearing the clap return is an echo.",
        formulaIds: ["echo-distance"],
        mistake: { wrong: "The distance to the wall is speed times the full echo time.", right: "Divide by two, because the sound makes a round trip." },
        check: { question: "Echo time is 2 s and the speed of sound is 340 m/s. How far is the wall?", answer: "340 m." },
        keyPoints: ["An echo is reflected sound.", "The path is there and back.", "d = vt/2.", "A minimum distance is needed for the echo to be heard separately."],
        worked: {
          prompt: "A person hears an echo after 2 s. The speed of sound is 340 m/s. How far is the wall?",
          formulaId: "echo-distance",
          known: { v: { value: 340, unit: "m/s" }, t: { value: 2, unit: "s" } },
          find: "d",
        },
        practice: [{ id: "c9-echo-p1", question: "Sound travels at 340 m/s. An echo returns in 1 s. Find the distance to the cliff.", hint: "Halve the round trip.", answer: "170 m.", worked: { formulaId: "echo-distance", known: { v: { value: 340, unit: "m/s" }, t: { value: 1, unit: "s" } }, find: "d" } }],
        quiz: [
          { id: "c9-echo-q1", question: "In the echo formula, we divide by 2 because…", choices: ["the sound travels to the wall and back", "sound has two frequencies", "there are two ears", "speed is always doubled"], answerIndex: 0, explanation: "The measured time is for the round trip." },
        ],
      },
    ],
  },
  {
    id: "c10-light",
    grade: 10,
    title: "Light",
    promise: "Mirrors and lenses form images. The sign convention matters.",
    scopeNote: "Class 10 ray optics. Object distance is negative in the school sign convention.",
    topics: [
      {
        id: "c10-mirror",
        title: "Spherical mirrors",
        aliases: ["concave mirror", "convex mirror", "mirror formula", "focal length"],
        idea: "A concave mirror can converge light. A convex mirror diverges it. The mirror formula is 1/v + 1/u = 1/f, with the school sign convention.",
        younger: "Object distance u is negative because the object is on the left. A concave mirror has a negative focal length. A real image has a negative v.",
        senior: "Do not enter a positive object distance and hope the checker will flip the sign. If the sign is missing, the result is not trustworthy.",
        example: "For a concave mirror with f = −15 cm and u = −30 cm, v = −30 cm. The image is real, inverted, and the same size.",
        formulaIds: ["mirror-formula", "mirror-magnification"],
        mistake: { wrong: "All distances in the mirror formula can be entered as positive numbers.", right: "The sign carries the direction. Object distance is negative." },
        check: { question: "In the usual sign convention, is the object distance positive or negative?", answer: "Negative." },
        keyPoints: ["1/v + 1/u = 1/f.", "u is negative.", "Concave f is negative.", "Convex f is positive.", "m = −v/u."],
        sketch: "mirror",
        worked: {
          prompt: "A concave mirror has f = −15 cm. An object is at u = −30 cm. Find v.",
          formulaId: "mirror-formula",
          known: { u: { value: -30, unit: "cm" }, f: { value: -15, unit: "cm" } },
          find: "v",
          after: "v = −30 cm, so the image is real and 30 cm in front of the mirror.",
        },
        practice: [{ id: "c10-mirror-p1", question: "Why will the checker refuse u = +30 cm for a mirror?", hint: "Think about the sign convention.", answer: "Object distance should be negative. The checker will not guess the sign." }],
        quiz: [
          { id: "c10-mirror-q1", question: "For a concave mirror in the school convention, f is…", choices: ["negative", "always zero", "measured in kilograms", "equal to the object height"], answerIndex: 0, explanation: "The focus is in front of the mirror, which is the negative side." },
          { id: "c10-mirror-q2", question: "The mirror formula is…", choices: ["1/v + 1/u = 1/f", "V = IR", "F = ma", "v = fλ"], answerIndex: 0, explanation: "That is the spherical-mirror relation." },
        ],
      },
      {
        id: "c10-lens",
        title: "Refraction and lenses",
        aliases: ["lens", "refraction", "convex lens", "power of a lens"],
        idea: "Refraction bends light when it enters a new medium. A convex lens can converge light. The lens formula is 1/v − 1/u = 1/f.",
        younger: "A convex lens has positive f and positive power. Power in dioptres is 1/f when f is in metres. A 20 cm convex lens has power +5 D.",
        senior: "Snell’s law uses angles from the normal. For air into a medium, n = sin i / sin r. Also n = c/v.",
        example: "A convex lens of focal length 0.25 m has power 4 D.",
        formulaIds: ["lens-formula", "lens-power", "refractive-index", "lens-magnification"],
        mistake: { wrong: "Power uses focal length in centimetres.", right: "Use metres. P = 1/f." },
        check: { question: "What is the power of a convex lens with f = 0.5 m?", answer: "+2 D." },
        keyPoints: ["Light bends at a boundary.", "1/v − 1/u = 1/f.", "Convex lenses have positive power.", "P = 1/f with f in metres.", "Angles in Snell’s law are from the normal."],
        worked: {
          prompt: "A convex lens has focal length 20 cm. Find its power.",
          formulaId: "lens-power",
          known: { f: { value: 20, unit: "cm" } },
          find: "P",
          after: "20 cm = 0.20 m, so P = 5 D. The lens is convex, so the power is positive.",
        },
        practice: [{ id: "c10-lens-p1", question: "Find the power of a lens with f = −0.25 m.", hint: "P = 1/f in metres.", answer: "−4 D. The negative sign means a concave lens.", worked: { formulaId: "lens-power", known: { f: { value: -0.25, unit: "m" } }, find: "P" } }],
        quiz: [
          { id: "c10-lens-q1", question: "A convex lens has power that is…", choices: ["positive", "always zero", "measured in ohms", "negative"], answerIndex: 0, explanation: "Convex lenses converge and have positive f." },
          { id: "c10-lens-q2", question: "Focal length must be in metres when calculating…", choices: ["power in dioptres", "mass", "echo time", "momentum"], answerIndex: 0, explanation: "P = 1/f gives dioptres only if f is in metres." },
        ],
      },
    ],
  },
  {
    id: "c10-eye",
    grade: 10,
    title: "The human eye",
    promise: "The eye focuses light, and defects have lens corrections.",
    scopeNote: "Class 10 eye. No invented prescriptions.",
    topics: [
      {
        id: "c10-eye",
        title: "How the eye focuses",
        aliases: ["eye", "ciliary", "retina"],
        idea: "The eye lens forms a real inverted image on the retina. Ciliary muscles change the lens shape so we can focus at different distances.",
        younger: "The brain learns to interpret the inverted image as upright. The power of accommodation is this ability to change focus.",
        example: "Looking from a distant board to a nearby book requires the eye lens to become more curved.",
        formulaIds: [],
        mistake: { wrong: "The image on the retina is upright, so no interpretation is needed.", right: "The image is real and inverted. The brain interprets it." },
        check: { question: "Where does a healthy eye form the image?", answer: "On the retina." },
        keyPoints: ["The image is real and inverted.", "It forms on the retina.", "The lens changes shape to focus.", "This change is accommodation."],
        practice: [{ id: "c10-eye-p1", question: "What muscles change the shape of the eye lens?", hint: "They are named in the lesson.", answer: "The ciliary muscles." }],
        quiz: [
          { id: "c10-eye-q1", question: "A healthy eye forms the image on the…", choices: ["retina", "iris only", "mirror", "cornea as a screen"], answerIndex: 0, explanation: "The retina is the screen of the eye." },
        ],
      },
      {
        id: "c10-defects",
        title: "Myopia and hypermetropia",
        aliases: ["myopia", "hypermetropia", "short sight", "long sight"],
        idea: "Myopia, or short sight, is corrected by a concave lens. Hypermetropia, or long sight, is corrected by a convex lens.",
        younger: "In myopia, distant objects are focused in front of the retina. A diverging lens spreads the rays so the focus can move back onto the retina.",
        example: "A person who sees a book clearly but not a distant board may have myopia.",
        formulaIds: ["lens-power"],
        mistake: { wrong: "Myopia is corrected with a convex lens.", right: "Myopia uses a concave lens. Hypermetropia uses a convex lens." },
        check: { question: "Which lens corrects long sight?", answer: "A convex lens." },
        keyPoints: ["Myopia: distant objects are blurred.", "Myopia uses a concave lens.", "Hypermetropia: nearby objects are blurred.", "Hypermetropia uses a convex lens."],
        practice: [{ id: "c10-defects-p1", question: "A correcting lens has power −2 D. Is it for myopia or hypermetropia?", hint: "Negative power means a concave lens.", answer: "Myopia, because the lens is concave." }],
        quiz: [
          { id: "c10-defects-q1", question: "Short sight is corrected by a…", choices: ["concave lens", "convex lens", "plane mirror", "prism only"], answerIndex: 0, explanation: "A diverging lens is used for myopia." },
          { id: "c10-defects-q2", question: "Positive power of a correcting lens fits…", choices: ["hypermetropia", "myopia", "a broken retina wire", "an echo"], answerIndex: 0, explanation: "Long sight needs a converging lens." },
        ],
      },
    ],
  },
  {
    id: "c10-electricity",
    grade: 10,
    title: "Electricity",
    promise: "Ohm’s law, series and parallel resistors, and electric power.",
    scopeNote: "Class 10. Ohm’s law needs constant temperature for that conductor.",
    topics: [
      {
        id: "c10-ohm",
        title: "Ohm’s law",
        aliases: ["ohm", "ohm's law", "resistance", "voltage", "current"],
        idea: "For a given conductor at constant temperature, V = IR. Current is the same through resistors in series. Potential difference is the same across resistors in parallel.",
        younger: "If a 5 ohm resistor carries 2 A, the potential difference is 10 V. Double the resistance at the same voltage and the current becomes half.",
        senior: "Ohm’s law is not a universal law for every device. A filament lamp can change resistance as it heats, so V and I are not proportional over a wide range.",
        example: "A current of 2 A through 5 ohm gives V = 10 V.",
        formulaIds: ["ohms-law", "series-resistance", "parallel-resistance"],
        mistake: { wrong: "In a series circuit, the current is used up as it passes each resistor.", right: "The current is the same through each series resistor. The potential drops add." },
        check: { question: "V = 12 V and R = 4 ohm. What is I?", answer: "3 A." },
        keyPoints: ["V = IR at constant temperature.", "Series resistances add.", "Parallel: 1/R = 1/R1 + 1/R2.", "Series current is the same.", "Parallel voltage is the same."],
        sketch: "circuit",
        worked: {
          prompt: "A current of 2 A flows through a 5 ohm resistor. Find the potential difference.",
          formulaId: "ohms-law",
          known: { I: { value: 2, unit: "A" }, R: { value: 5, unit: "ohm" } },
          find: "V",
        },
        practice: [{ id: "c10-ohm-p1", question: "Two resistors, 2 ohm and 3 ohm, are in series. Find the equivalent resistance.", hint: "Add them.", answer: "5 ohm.", worked: { formulaId: "series-resistance", known: { R1: { value: 2, unit: "ohm" }, R2: { value: 3, unit: "ohm" } }, find: "R" } }],
        quiz: [
          { id: "c10-ohm-q1", question: "Ohm’s law is written…", choices: ["V = IR", "F = ma", "v = fλ", "P = F/A"], answerIndex: 0, explanation: "Potential difference equals current times resistance." },
          { id: "c10-ohm-q2", question: "Two equal resistors in parallel have an equivalent resistance that is…", choices: ["half of one of them", "their sum", "zero", "double their sum"], answerIndex: 0, explanation: "1/R = 1/R1 + 1/R1 gives R = R1/2." },
        ],
      },
      {
        id: "c10-power",
        title: "Electric power and heating",
        aliases: ["electric power", "joule", "heating"],
        idea: "Electric power is P = VI. When Ohm’s law holds, P = I²R = V²/R. Heat produced in a resistor is H = I²Rt.",
        younger: "A brighter lamp of the same kind usually uses more power. The heating formula uses the current through that resistor, its resistance, and the time.",
        example: "A 2 A current in a 5 ohm heater for 10 s produces 200 J of heat.",
        formulaIds: ["electric-power", "joule-heat"],
        mistake: { wrong: "P = I²R and P = V²/R can be used even when V is not IR for that resistor.", right: "Those forms match only when Ohm’s law holds for the same resistor." },
        check: { question: "How much heat does 1 A produce in 4 ohm in 5 s?", answer: "20 J." },
        keyPoints: ["P = VI.", "Also P = I²R = V²/R when V = IR.", "H = I²Rt.", "Energy and heat here are in joules."],
        worked: {
          prompt: "A 2 A current flows through 5 ohm for 10 s. How much heat is produced?",
          formulaId: "joule-heat",
          known: { I: { value: 2, unit: "A" }, R: { value: 5, unit: "ohm" }, t: { value: 10, unit: "s" } },
          find: "H",
        },
        practice: [{ id: "c10-power-p1", question: "A device works at 6 V and 2 A. Find the power.", hint: "P = VI.", answer: "12 W.", worked: { formulaId: "electric-power", known: { V: { value: 6, unit: "V" }, I: { value: 2, unit: "A" } }, find: "P" } }],
        quiz: [
          { id: "c10-power-q1", question: "H = I²Rt gives heat in joules when I, R, and t are in…", choices: ["amperes, ohms, and seconds", "kilograms only", "metres only", "dioptres"], answerIndex: 0, explanation: "Those are the SI units for this formula." },
        ],
      },
    ],
  },
  {
    id: "c10-magnetism",
    grade: 10,
    title: "Magnetic effects of current",
    promise: "A current produces a magnetic field. A changing field can induce a current.",
    scopeNote: "Class 10 qualitative magnetic effects. The force formulas are developed in Class 12.",
    topics: [
      {
        id: "c10-field",
        title: "Magnetic field of a current",
        aliases: ["magnetic field", "solenoid", "right hand"],
        idea: "A current-carrying wire produces a magnetic field. A coil, or solenoid, has a field like a bar magnet while the current flows.",
        younger: "The direction of the field around a straight wire can be found with the right-hand rule. Reverse the current and the field reverses.",
        example: "An electromagnet in a crane picks up iron only while the current is on.",
        formulaIds: [],
        mistake: { wrong: "A wire with no current still has the same magnetic field as a current-carrying wire.", right: "The field described here is produced by the current." },
        check: { question: "What happens to a simple electromagnet when the current is switched off?", answer: "It stops acting as that electromagnet." },
        keyPoints: ["Current produces a magnetic field.", "A solenoid resembles a bar magnet.", "Reversing current reverses the field.", "An electromagnet can be switched off."],
        sketch: "magnet",
        practice: [{ id: "c10-field-p1", question: "Why can a crane drop the iron scrap?", hint: "Think about the current.", answer: "The current in the electromagnet is switched off." }],
        quiz: [
          { id: "c10-field-q1", question: "A magnetic field appears around a wire when the wire has…", choices: ["a current", "no charges at all", "only a colour", "a shadow"], answerIndex: 0, explanation: "Moving charge, as a current, produces the field." },
        ],
      },
      {
        id: "c10-induction",
        title: "Electromagnetic induction",
        aliases: ["induction", "generator", "fleming"],
        idea: "A changing magnetic field through a coil induces an emf. Generators use this effect. Motors use the force on a current in a magnetic field.",
        younger: "Moving a magnet into a coil makes the galvanometer kick. Holding the magnet still inside the coil does not keep the current flowing.",
        example: "A bicycle dynamo turns a magnet near a coil and produces a current while you pedal.",
        formulaIds: ["faraday"],
        mistake: { wrong: "A steady magnet sitting still in a coil keeps inducing a steady current.", right: "The flux has to change. A still magnet gives no induced emf." },
        check: { question: "Does a stationary magnet in a stationary coil induce an emf?", answer: "No, because the flux is not changing." },
        keyPoints: ["Induction needs a changing magnetic flux.", "A generator converts motion into electrical energy.", "A motor converts electrical energy into motion.", "Fleming’s rules give directions in school problems."],
        practice: [{ id: "c10-induction-p1", question: "Why does the induced current stop when you stop moving the magnet?", hint: "What must change?", answer: "The magnetic flux through the coil is no longer changing." }],
        quiz: [
          { id: "c10-induction-q1", question: "An emf is induced when magnetic flux is…", choices: ["changing", "zero and staying zero", "a kind of sound", "constant and large"], answerIndex: 0, explanation: "Faraday’s law depends on the change in flux." },
        ],
      },
    ],
  },
];
