import type { Chapter } from "../types";

export const seniorChapters: Chapter[] = [
  {
    id: "c11-units",
    grade: 11,
    title: "Units and measurement",
    promise: "SI units and significant figures keep a measurement honest.",
    scopeNote: "Class 11 measurement. The checker does not invent extra precision.",
    topics: [
      {
        id: "c11-si",
        title: "SI units",
        aliases: ["si unit", "base unit", "dimension"],
        idea: "The SI base units include the metre, kilogram, second, ampere, kelvin, mole, and candela. A derived unit is built from these, such as the newton or the joule.",
        younger: "Write the unit with the number. An equation is wrong if the two sides do not have the same dimensions.",
        senior: "Use dimensions to check a formula, not to prove it is the correct physical law. Different correct formulas can share the same dimensions.",
        example: "Force has dimensions of mass × length / time², which matches the newton.",
        formulaIds: [],
        mistake: { wrong: "A dimensionally correct formula must be the right law.", right: "Dimensional agreement is necessary, but it cannot fix a missing dimensionless number such as 1/2." },
        check: { question: "Is the newton a base unit or a derived unit?", answer: "Derived. It is kg m/s²." },
        keyPoints: ["Base units include m, kg, s, A, and K.", "The newton and joule are derived.", "Both sides of an equation need the same dimensions.", "A dimension check cannot prove a formula."],
        practice: [{ id: "c11-si-p1", question: "Why is 5 kg + 5 m meaningless?", hint: "Compare dimensions.", answer: "Mass and length are different quantities, so they cannot be added." }],
        quiz: [
          { id: "c11-si-q1", question: "The newton is equivalent to…", choices: ["kg m/s²", "kg/m", "J/s²", "A/s"], answerIndex: 0, explanation: "From F = ma." },
          { id: "c11-si-q2", question: "Dimensional analysis can…", choices: ["reject a formula with inconsistent dimensions", "prove every dimensionless factor", "replace an experiment", "measure g by itself"], answerIndex: 0, explanation: "It is a check, not a derivation of pure numbers." },
        ],
      },
      {
        id: "c11-sigfigs",
        title: "Significant figures",
        aliases: ["significant figures", "precision", "uncertainty"],
        idea: "Significant figures show the precision of a measurement. A calculated result should not look more precise than the data.",
        younger: "Non-zero digits count. Zeros between them count. Leading zeros in 0.0025 do not count. Trailing zeros count when a decimal point shows they were measured.",
        senior: "In multiplication and division, the result has as many significant figures as the least precise factor. In addition, the limiting precision is the least precise decimal place.",
        example: "1.2 × 3.46 should be reported as 4.2, not 4.152, if 1.2 has two significant figures.",
        formulaIds: [],
        mistake: { wrong: "A calculator’s full display is always the scientific answer.", right: "Round to the precision justified by the measurements." },
        check: { question: "How many significant figures are in 0.00450?", answer: "Three: 4, 5, and the trailing 0." },
        keyPoints: ["Significant figures record precision.", "Leading zeros do not count.", "Do not over-report calculator digits.", "Addition and multiplication use different rounding rules."],
        practice: [{ id: "c11-sigfigs-p1", question: "How many significant figures are in 1050 if the zero is only a placeholder and no decimal point is written?", hint: "Trailing zeros without a decimal are ambiguous. Say what you can be sure of.", answer: "It is ambiguous. 1 and 5 are significant, and the middle 0 is significant. The last 0 may only hold the place. Scientific notation, 1.050 × 10³, would make four figures clear." }],
        quiz: [
          { id: "c11-sigfigs-q1", question: "Leading zeros in 0.0032…", choices: ["are not significant", "are the most significant", "count as three figures by themselves", "mean the number is exact"], answerIndex: 0, explanation: "They only locate the decimal point." },
        ],
      },
    ],
  },
  {
    id: "c11-mechanics",
    grade: 11,
    title: "Laws, work, and energy",
    promise: "Net force, friction, work, and power for straight-line problems.",
    scopeNote: "Class 11 mechanics that the checker can verify. Circular-motion direction still needs a diagram.",
    topics: [
      {
        id: "c11-friction",
        title: "Friction and Newton’s second law",
        aliases: ["friction", "free body", "net force", "mu"],
        idea: "Draw the forces on one body. The net force is ma. Kinetic friction has magnitude μₖN and opposes sliding. μₛN is the maximum static friction, not always the actual value.",
        younger: "On level ground with no other vertical forces, N = mg. A pulled block accelerates only if the pull is greater than the friction that opposes it.",
        senior: "Do not put the third-law partner on the same free-body diagram. Static friction adjusts up to μₛN. If the required friction is smaller, the block stays at rest.",
        example: "If μₖ = 0.2 and N = 20 N, the kinetic friction is 4 N.",
        formulaIds: ["friction", "newton-second", "weight"],
        mistake: { wrong: "Static friction is always equal to μₛN.", right: "μₛN is the largest static friction. The actual value can be smaller." },
        check: { question: "Kinetic friction is 0.25 × 40 N. What is its magnitude?", answer: "10 N." },
        keyPoints: ["Use a free-body diagram.", "F_net = ma.", "fₖ = μₖN.", "Static friction ≤ μₛN.", "Friction opposes relative motion."],
        worked: {
          prompt: "The normal force is 20 N and μₖ = 0.2. Find the kinetic friction.",
          formulaId: "friction",
          known: { mu: { value: 0.2, unit: "1" }, N: { value: 20, unit: "N" } },
          find: "f",
        },
        practice: [{ id: "c11-friction-p1", question: "A 2 kg block on level ground has μₖ = 0.1. Take g = 10 m/s². Find the kinetic friction.", hint: "First find N = mg.", answer: "N = 20 N, so friction = 2 N." }],
        quiz: [
          { id: "c11-friction-q1", question: "μₛN is…", choices: ["the maximum static friction", "always the friction while the block is at rest", "a speed", "a displacement"], answerIndex: 0, explanation: "The actual static friction can be smaller than the maximum." },
        ],
      },
      {
        id: "c11-power",
        title: "Work and power",
        aliases: ["power", "work energy", "joule", "watt"],
        idea: "The work-energy idea: the net work done on a body equals its change in kinetic energy when the work accounts for the forces in the model. Power is work divided by time.",
        younger: "A motor that does 1000 J of work in 2 s has a power of 500 W. One watt is one joule per second.",
        senior: "W = Fs cosθ is for a constant force. If the force changes, you need the area under the force-displacement graph, which this checker will not invent.",
        example: "Lifting slowly at constant speed means the net work is zero, while your lifting force still does positive work and gravity does negative work.",
        formulaIds: ["work", "power", "kinetic-energy"],
        mistake: { wrong: "Power and work are the same unit.", right: "Work is in joules. Power is in watts, joules per second." },
        check: { question: "A machine does 600 J in 3 s. What is its power?", answer: "200 W." },
        keyPoints: ["Power = work / time.", "1 W = 1 J/s.", "Separate the work of each force.", "Constant-force work is Fs cosθ."],
        worked: {
          prompt: "A pump does 2000 J of work in 4 s. Find the power.",
          formulaId: "power",
          known: { W: { value: 2000, unit: "J" }, t: { value: 4, unit: "s" } },
          find: "P",
        },
        practice: [{ id: "c11-power-p1", question: "A force of 20 N moves an object 3 m in the same direction in 5 s. Find the power.", hint: "Find the work first, then divide by time.", answer: "Work is 60 J, so power is 12 W." }],
        quiz: [
          { id: "c11-power-q1", question: "The watt is a unit of…", choices: ["power", "force", "charge", "wavelength"], answerIndex: 0, explanation: "Power is the rate of doing work." },
        ],
      },
    ],
  },
  {
    id: "c11-oscillations",
    grade: 11,
    title: "Oscillations and waves",
    promise: "A pendulum and a spring have periods the checker can test.",
    scopeNote: "Small oscillations only. The simple-pendulum formula fails for large swings.",
    topics: [
      {
        id: "c11-pendulum",
        title: "Simple pendulum and spring",
        aliases: ["pendulum", "spring", "time period", "shm"],
        idea: "For small swings, a simple pendulum has T = 2π√(L/g). A mass on a spring has T = 2π√(m/k). Neither period depends on the amplitude in this ideal model.",
        younger: "A longer pendulum has a longer period. A heavier bob does not change the ideal pendulum period. A stiffer spring oscillates faster.",
        senior: "The pendulum result is an approximation for small angles. The spring formula ignores the mass of the spring and assumes Hooke’s law.",
        example: "A 1 m pendulum near Earth has a period a little over 2 s.",
        formulaIds: ["pendulum-period", "spring-period", "shm-velocity"],
        mistake: { wrong: "A heavier pendulum bob has a longer period.", right: "In the ideal formula, the bob’s mass cancels and does not appear." },
        check: { question: "If the length of a pendulum becomes four times, what happens to the period?", answer: "It doubles, because of the square root." },
        keyPoints: ["Pendulum: T = 2π√(L/g).", "The bob’s mass does not appear.", "Spring: T = 2π√(m/k).", "Both formulas are for the ideal small oscillation."],
        sketch: "pendulum",
        worked: {
          prompt: "Find the period of a 1.0 m simple pendulum. Take g = 9.8 m/s².",
          formulaId: "pendulum-period",
          known: { L: { value: 1, unit: "m" }, g: { value: 9.8, unit: "m/s²" } },
          find: "T",
          after: "The period is about 2.01 s. The mass of the bob was not needed.",
        },
        practice: [{ id: "c11-pendulum-p1", question: "A spring has k = 100 N/m and the mass is 1 kg. Find the period.", hint: "T = 2π√(m/k).", answer: "About 0.628 s.", worked: { formulaId: "spring-period", known: { m: { value: 1, unit: "kg" }, k: { value: 100, unit: "N/m" } }, find: "T" } }],
        quiz: [
          { id: "c11-pendulum-q1", question: "The ideal simple-pendulum period does not depend on…", choices: ["the mass of the bob", "the length", "g", "the square root of the length"], answerIndex: 0, explanation: "Mass cancels in the derivation." },
          { id: "c11-pendulum-q2", question: "Quadrupling the pendulum length multiplies the period by…", choices: ["2", "4", "16", "1/2"], answerIndex: 0, explanation: "Period follows the square root of length." },
        ],
      },
      {
        id: "c11-waves",
        title: "Wave speed and beats",
        aliases: ["wave", "beats", "superposition"],
        idea: "A travelling wave has speed v = fλ. Two close frequencies heard together produce beats at |f1 − f2|.",
        younger: "Beats are the loud-soft throbbing. If one fork is 256 Hz and the other is 260 Hz, you hear 4 beats each second.",
        senior: "The beat formula gives the frequency of loudness variation, not a new musical note at that low frequency in the simple school model.",
        example: "A 2 m wave passing at 10 m/s has frequency 5 Hz.",
        formulaIds: ["wave-speed", "beats"],
        mistake: { wrong: "Beat frequency is the sum of the two frequencies.", right: "It is the absolute difference." },
        check: { question: "Forks of 340 Hz and 344 Hz sound together. What is the beat frequency?", answer: "4 Hz." },
        keyPoints: ["v = fλ.", "Beats need two close frequencies.", "Beat frequency = |f1 − f2|.", "The wave speed depends on the medium."],
        practice: [{ id: "c11-waves-p1", question: "A wave of frequency 50 Hz has wavelength 0.4 m. Find the speed.", hint: "Multiply.", answer: "20 m/s.", worked: { formulaId: "wave-speed", known: { f: { value: 50, unit: "Hz" }, lambda: { value: 0.4, unit: "m" } }, find: "v" } }],
        quiz: [
          { id: "c11-waves-q1", question: "Frequencies 500 Hz and 504 Hz produce a beat frequency of…", choices: ["4 Hz", "502 Hz", "1004 Hz", "0 Hz"], answerIndex: 0, explanation: "The absolute difference is 4 Hz." },
        ],
      },
    ],
  },
  {
    id: "c11-heat",
    grade: 11,
    title: "Heat and thermodynamics",
    promise: "Specific heat and the first law, with the school sign convention.",
    scopeNote: "NCERT writes ΔQ = ΔU + ΔW, with ΔW the work done by the system.",
    topics: [
      {
        id: "c11-specific",
        title: "Specific heat",
        aliases: ["specific heat", "calorimetry", "q = mcdt"],
        idea: "The heat needed for a temperature change, with no change of state, is Q = mcΔT. c is the specific heat capacity.",
        younger: "Water’s specific heat is about 4180 J/kg°C, so it takes a lot of energy to warm water. ΔT in °C and in K is the same number.",
        senior: "This formula is not the latent-heat formula. Melting and boiling at constant temperature use Q = mL instead, and this checker will not swap the two.",
        example: "Heating 0.5 kg of water by 2°C needs about 4180 J if c = 4180 J/kg°C.",
        formulaIds: ["heat-capacity"],
        mistake: { wrong: "Use Q = mcΔT while ice is melting at 0°C.", right: "During the change of state, use the latent heat. The temperature is not changing." },
        check: { question: "What does ΔT mean in Q = mcΔT?", answer: "The temperature change, not the starting temperature." },
        keyPoints: ["Q = mcΔT with no change of state.", "c is a property of the material.", "A change of state uses latent heat.", "A temperature change of 1°C equals 1 K."],
        sketch: "heat",
        worked: {
          prompt: "How much heat raises 2 kg of a material with c = 500 J/kg°C by 4°C?",
          formulaId: "heat-capacity",
          known: { m: { value: 2, unit: "kg" }, c: { value: 500, unit: "J/kg°C" }, dT: { value: 4, unit: "°C" } },
          find: "Q",
        },
        practice: [{ id: "c11-specific-p1", question: "Find Q for 1 kg, c = 400 J/kg°C, and a rise of 5°C.", hint: "Multiply the three numbers.", answer: "2000 J.", worked: { formulaId: "heat-capacity", known: { m: { value: 1, unit: "kg" }, c: { value: 400, unit: "J/kg°C" }, dT: { value: 5, unit: "°C" } }, find: "Q" } }],
        quiz: [
          { id: "c11-specific-q1", question: "Q = mcΔT should not be used when…", choices: ["the substance is changing state at constant temperature", "the temperature rises", "the mass is known", "c is known"], answerIndex: 0, explanation: "Latent heat applies during the change of state." },
        ],
      },
      {
        id: "c11-first-law",
        title: "First law",
        aliases: ["first law", "internal energy", "thermodynamics"],
        idea: "In the school sign convention, heat added to the system equals the rise in internal energy plus the work done by the system: ΔQ = ΔU + ΔW.",
        younger: "Energy is conserved. If a gas is heated and it expands, some of the heat becomes work done by the gas and some stays as internal energy.",
        senior: "Other books write the work sign the opposite way. Match the convention in the question before you move a term. This tutor uses the NCERT form.",
        example: "If 100 J is added and the system does 30 J of work, ΔU = 70 J.",
        formulaIds: ["first-law", "ideal-gas"],
        mistake: { wrong: "Work done by the system and work done on the system are the same sign in every textbook.", right: "Check the convention. Here ΔW is work done by the system." },
        check: { question: "ΔQ = 50 J and ΔW = 20 J. What is ΔU in this sign convention?", answer: "30 J." },
        keyPoints: ["ΔQ = ΔU + ΔW in this course.", "ΔW is work done by the system.", "Internal energy is a state function.", "Do not mix sign conventions."],
        practice: [{ id: "c11-first-law-p1", question: "A system absorbs 80 J and does 25 J of work. Find ΔU.", hint: "ΔU = ΔQ − ΔW.", answer: "55 J." }],
        quiz: [
          { id: "c11-first-law-q1", question: "In the convention used here, ΔW means work done…", choices: ["by the system", "only on the surroundings’ thermometer", "by friction always", "by the observer"], answerIndex: 0, explanation: "That is the NCERT choice stated in the formula notes." },
        ],
      },
    ],
  },
  {
    id: "c12-electrostatics",
    grade: 12,
    title: "Electrostatics",
    promise: "Coulomb’s law and capacitance, with constants stated.",
    scopeNote: "Class 12. k = 9 × 10⁹ N m²/C² in air or vacuum unless the question says otherwise.",
    topics: [
      {
        id: "c12-coulomb",
        title: "Coulomb’s law",
        aliases: ["coulomb", "charge", "electrostatic force"],
        idea: "In air or vacuum, the force magnitude between point charges is k|q1 q2|/r². Like charges repel and unlike charges attract.",
        younger: "Doubling the separation makes the force one quarter, because of the square. The checker reports the magnitude. The direction comes from the signs of the charges.",
        senior: "k = 1/(4πε₀) = 9 × 10⁹ N m²/C². Do not use this k inside a dielectric without the dielectric constant. Superposition adds forces as vectors, which a single number cannot do.",
        example: "Two charges of 1 μC separated by 1 m repel with a force of 9 × 10⁻³ N if they have the same sign.",
        formulaIds: ["coulomb", "electric-field", "potential-point"],
        mistake: { wrong: "The force falls to half when the distance doubles.", right: "It falls to a quarter because the distance is squared." },
        check: { question: "If both charges are positive, do they attract or repel?", answer: "They repel." },
        keyPoints: ["F = k|q1 q2|/r².", "k = 9 × 10⁹ in air or vacuum.", "Like charges repel.", "The inverse-square law is not an inverse law.", "Vector addition is needed for more than two charges."],
        worked: {
          prompt: "Two charges of 1 μC are 1 m apart in air. Find the force magnitude.",
          formulaId: "coulomb",
          known: { q1: { value: 1, unit: "μC" }, q2: { value: 1, unit: "μC" }, r: { value: 1, unit: "m" } },
          find: "F",
          after: "The magnitude is 0.009 N. The direction is repulsive if the charges have the same sign.",
        },
        practice: [{ id: "c12-coulomb-p1", question: "What happens to the Coulomb force if r is doubled and the charges stay the same?", hint: "Look at r².", answer: "It becomes one quarter." }],
        quiz: [
          { id: "c12-coulomb-q1", question: "Like charges…", choices: ["repel", "always attract", "have no force", "cancel Coulomb’s constant"], answerIndex: 0, explanation: "Same signs repel." },
          { id: "c12-coulomb-q2", question: "Doubling only the separation multiplies the force by…", choices: ["1/4", "1/2", "2", "4"], answerIndex: 0, explanation: "The force depends on 1/r²." },
        ],
      },
      {
        id: "c12-capacitor",
        title: "Capacitance",
        aliases: ["capacitance", "capacitor", "dielectric"],
        idea: "Capacitance is C = Q/V. The energy stored is ½CV². A vacuum parallel-plate capacitor has C = ε₀A/d, and a dielectric of constant K multiplies C by K.",
        younger: "A capacitor stores charge and energy. A larger plate area stores more charge at the same voltage. A larger gap stores less.",
        senior: "The three energy expressions ½CV², ½QV, and Q²/(2C) agree only for the same capacitor at the same moment. Do not mix values from before and after a dielectric is inserted unless you know what is held constant.",
        example: "A 2 μF capacitor at 10 V stores 100 μJ, which is 1 × 10⁻⁴ J.",
        formulaIds: ["capacitance", "capacitor-energy", "parallel-plate"],
        mistake: { wrong: "Inserting a dielectric always raises the voltage.", right: "It multiplies C by K. The voltage falls if the charge is held fixed, because V = Q/C." },
        check: { question: "A capacitor holds 6 μC at 3 V. What is C?", answer: "2 μF." },
        keyPoints: ["C = Q/V.", "Energy stored = ½CV².", "C = ε₀A/d in vacuum.", "A dielectric multiplies C by K.", "Say whether Q or V is held constant."],
        practice: [{ id: "c12-capacitor-p1", question: "Find the energy stored in a 2 μF capacitor charged to 10 V.", hint: "Use ½CV² and convert microfarads.", answer: "1 × 10⁻⁴ J." }],
        quiz: [
          { id: "c12-capacitor-q1", question: "Capacitance is…", choices: ["charge stored per volt", "force per metre", "current per second only", "wavelength per slit"], answerIndex: 0, explanation: "C = Q/V." },
        ],
      },
    ],
  },
  {
    id: "c12-current",
    grade: 12,
    title: "Current and magnetism",
    promise: "Drift speed, resistivity, and the magnetic force on a moving charge.",
    scopeNote: "Class 12. Magnetic force does no work because it is perpendicular to velocity.",
    topics: [
      {
        id: "c12-resistivity",
        title: "Current and resistivity",
        aliases: ["resistivity", "drift speed", "current electricity"],
        idea: "Current in a wire is I = neAv_d. Resistance of a uniform wire is R = ρl/A. Resistivity is a property of the material.",
        younger: "A longer wire has more resistance. A thicker wire has less. Drift speed is surprisingly small, while the electric field starts the current through the wire quickly.",
        senior: "n is the number of free electrons per cubic metre, not the number in the whole wire. ρ and resistance are different: resistance also depends on shape.",
        example: "Doubling the length of a uniform wire doubles its resistance if the material and area stay the same.",
        formulaIds: ["drift-current", "resistivity", "ohms-law"],
        mistake: { wrong: "Resistivity depends on the length of the particular wire.", right: "Resistivity belongs to the material. Length changes the resistance." },
        check: { question: "A wire is stretched to twice its length with the volume kept constant. What happens to its resistance, qualitatively?", answer: "It rises. The length doubles and the area falls, so R = ρl/A increases by more than a factor of two. This checker will not guess the factor unless the new area is given." },
        keyPoints: ["I = neAv_d.", "R = ρl/A.", "ρ is a material property.", "Drift speed is small.", "Ohm’s law still needs the right temperature."],
        practice: [{ id: "c12-resistivity-p1", question: "A wire has ρ = 1.5 × 10⁻⁸ Ω m in the data book sense, but only l and A are given in a problem as 2 m and 1 mm². What else would you need before quoting R?", hint: "Look at R = ρl/A.", answer: "You need the resistivity as well as the length and area. If ρ is not in the question, do not invent a metal." }],
        quiz: [
          { id: "c12-resistivity-q1", question: "Resistance of a uniform wire increases when…", choices: ["its length increases", "its area increases", "its resistivity becomes zero", "the drift speed formula loses n"], answerIndex: 0, explanation: "R is proportional to length." },
        ],
      },
      {
        id: "c12-lorentz",
        title: "Magnetic force",
        aliases: ["lorentz", "magnetic force", "cyclotron"],
        idea: "A charge moving in a magnetic field feels F = qvB sinθ. The force is zero when v is parallel to B, and it does no work because it is perpendicular to the velocity.",
        younger: "A current-carrying wire feels F = IlB sinθ. The direction comes from Fleming’s left-hand rule in school problems. The checker can check a magnitude only when θ and the values are given.",
        senior: "Because the magnetic force is perpendicular to v, it changes direction, not speed. Circular motion in a uniform field has r = mv/(qB) when v is perpendicular to B. Ask for the radius only if m, v, q, and B are all known.",
        example: "A charge moving parallel to a magnetic field feels no magnetic force.",
        formulaIds: ["lorentz", "wire-force"],
        mistake: { wrong: "A magnetic field speeds a charged particle up.", right: "The magnetic force does no work, so it does not change the kinetic energy." },
        check: { question: "When is the magnetic force on a moving charge zero?", answer: "When the velocity is parallel or opposite to the field, or the charge is at rest." },
        keyPoints: ["F = qvB sinθ.", "Parallel motion means zero magnetic force.", "The magnetic force does no work.", "A wire feels F = IlB sinθ.", "Direction needs a rule, not only a magnitude."],
        practice: [{ id: "c12-lorentz-p1", question: "Why does a magnetic force not change a particle’s kinetic energy?", hint: "Look at the angle between F and v.", answer: "The force is perpendicular to the velocity, so its work is zero." }],
        quiz: [
          { id: "c12-lorentz-q1", question: "A charge at rest in a magnetic field feels…", choices: ["no magnetic force", "a force qB", "a force equal to its weight always", "an induced nuclear force"], answerIndex: 0, explanation: "v = 0 makes F = 0." },
        ],
      },
    ],
  },
  {
    id: "c12-induction",
    grade: 12,
    title: "Induction and alternating current",
    promise: "Faraday’s law and the ideal transformer.",
    scopeNote: "Class 12. The ideal transformer wastes no energy. Real transformers do.",
    topics: [
      {
        id: "c12-faraday",
        title: "Faraday and Lenz",
        aliases: ["faraday", "lenz", "induced emf", "flux"],
        idea: "The induced emf equals the negative rate of change of magnetic flux. The minus sign is Lenz’s law: the induced current opposes the change that causes it.",
        younger: "Pushing a north pole into a coil makes the coil’s near face act like a north pole, so it repels the incoming magnet. That opposition is Lenz’s law.",
        senior: "Flux is B times area only for a uniform field perpendicular to a flat area. If the angle or the field is unknown, the checker should not invent Φ.",
        example: "If the flux through a coil falls by 0.2 Wb in 0.1 s, the average induced emf magnitude is 2 V.",
        formulaIds: ["faraday"],
        mistake: { wrong: "Lenz’s law says the induced current attracts every approaching magnet.", right: "It opposes the change. An approaching north pole is repelled." },
        check: { question: "What does the induced current oppose?", answer: "The change in flux that produces it." },
        keyPoints: ["emf = −ΔΦ/Δt.", "The minus sign is Lenz’s law.", "A still flux means no induced emf.", "Opposition conserves energy."],
        practice: [{ id: "c12-faraday-p1", question: "The flux changes by 0.5 Wb in 0.25 s. What is the magnitude of the average induced emf?", hint: "Divide the change by the time.", answer: "2 V." }],
        quiz: [
          { id: "c12-faraday-q1", question: "Lenz’s law is about…", choices: ["the direction that opposes the change", "the colour of the magnet", "Ohm’s law at constant temperature", "the eye lens"], answerIndex: 0, explanation: "The induced effect opposes the flux change." },
        ],
      },
      {
        id: "c12-transformer",
        title: "Transformers and RMS values",
        aliases: ["transformer", "rms", "alternating current"],
        idea: "An ideal transformer obeys Vs/Vp = Ns/Np. Household 220 V is an RMS value, not the peak. V_rms = V₀/√2.",
        younger: "A step-down transformer has fewer turns on the secondary, so the secondary voltage is smaller. It does not create energy. A step-up in voltage means a step-down in current for an ideal transformer.",
        senior: "The ideal relation ignores resistance and flux leakage. A transformer works with changing current, so it is used with AC, not with steady DC.",
        example: "A transformer with 400 primary turns and 100 secondary turns changes 220 V to 55 V if it is ideal.",
        formulaIds: ["transformer", "ac-rms", "impedance"],
        mistake: { wrong: "A transformer changes a steady DC voltage in the same ratio.", right: "A steady DC primary current does not change the flux, so there is no induced secondary emf." },
        check: { question: "Vp = 220 V, Np = 400, Ns = 100. What is Vs for an ideal transformer?", answer: "55 V." },
        keyPoints: ["Vs/Vp = Ns/Np for an ideal transformer.", "Fewer secondary turns means a step down.", "220 V mains is RMS.", "Transformers need a changing flux, so AC."],
        worked: {
          prompt: "An ideal transformer has Vp = 220 V, Np = 400, and Ns = 100. Find Vs.",
          formulaId: "transformer",
          known: { Vp: { value: 220, unit: "V" }, Np: { value: 400, unit: "1" }, Ns: { value: 100, unit: "1" } },
          find: "Vs",
        },
        practice: [{ id: "c12-transformer-p1", question: "The peak voltage is 10√2 V. What is the RMS voltage?", hint: "Divide the peak by √2.", answer: "10 V." }],
        quiz: [
          { id: "c12-transformer-q1", question: "A step-down transformer has…", choices: ["fewer secondary turns than primary turns", "no core and steady DC", "Ns greater than Np always", "Vs larger than Vp"], answerIndex: 0, explanation: "The voltage ratio equals the turns ratio." },
          { id: "c12-transformer-q2", question: "The 220 V of household supply is…", choices: ["an RMS value", "the peak value", "a DC value", "a magnetic field"], answerIndex: 0, explanation: "AC ratings are RMS unless a question says peak." },
        ],
      },
    ],
  },
  {
    id: "c12-modern",
    grade: 12,
    title: "Waves, quanta, and nuclei",
    promise: "Fringe width, the photoelectric equation, de Broglie wavelength, and half-life.",
    scopeNote: "Class 12 modern physics. If hf is below the work function, no electrons leave.",
    topics: [
      {
        id: "c12-optics",
        title: "Young’s fringes",
        aliases: ["young", "fringe", "interference", "double slit"],
        idea: "In Young’s double-slit experiment the bright-fringe spacing is β = λD/d. A larger wavelength or a farther screen spreads the fringes. A wider slit gap packs them closer.",
        younger: "The pattern is interference of two waves from the slits. Red light makes wider fringes than blue light if D and d stay the same.",
        senior: "The formula assumes D is much larger than d and the slits are narrow. Do not use it for a single-slit diffraction width.",
        example: "λ = 600 nm, D = 1 m, and d = 0.3 mm give a fringe width of 2 mm.",
        formulaIds: ["young-fringe"],
        mistake: { wrong: "Moving the screen closer increases the fringe width.", right: "β is proportional to D, so a closer screen makes the fringes narrower." },
        check: { question: "What happens to β if the wavelength is doubled and nothing else changes?", answer: "β doubles." },
        keyPoints: ["β = λD/d.", "Wider gap, narrower fringes.", "This is double-slit interference.", "Use metres in the checker."],
        worked: {
          prompt: "λ = 600 nm, D = 1.5 m, and d = 0.3 mm. Find the fringe width.",
          formulaId: "young-fringe",
          known: { lambda: { value: 600, unit: "nm" }, D: { value: 1.5, unit: "m" }, d: { value: 0.3, unit: "mm" } },
          find: "beta",
        },
        practice: [{ id: "c12-optics-p1", question: "Why does red light give wider double-slit fringes than blue light in the same apparatus?", hint: "Compare wavelengths.", answer: "Red light has a longer wavelength, and β is proportional to λ." }],
        quiz: [
          { id: "c12-optics-q1", question: "Fringe width increases when…", choices: ["wavelength increases", "slit separation increases", "the screen is brought closer", "frequency increases and wavelength falls"], answerIndex: 0, explanation: "β is proportional to λ and D, and inversely proportional to d." },
        ],
      },
      {
        id: "c12-photo",
        title: "Photons and matter waves",
        aliases: ["photoelectric", "photon", "work function", "de broglie"],
        idea: "K_max = hf − φ. If hf is less than the work function, no electrons leave. A moving particle has a de Broglie wavelength λ = h/p.",
        younger: "Brighter light means more photons, so more electrons can leave, but it does not raise the maximum kinetic energy. Higher frequency does.",
        senior: "h = 6.626 × 10⁻³⁴ J s. A stopping potential measures K_max in electronvolts through eV_s. Do not convert eV unless the question uses them. Intensity cannot create emission below the threshold frequency.",
        example: "Above threshold, doubling the frequency does not simply double K_max, because the work function is subtracted.",
        formulaIds: ["einstein-photo", "de-broglie"],
        mistake: { wrong: "A brighter beam below the threshold frequency will eventually eject electrons.", right: "Each photon is still too small. Brightness does not raise hf." },
        check: { question: "What changes K_max: making the light brighter, or raising its frequency above threshold?", answer: "Raising the frequency. Brightness changes the number of electrons, not K_max." },
        keyPoints: ["K_max = hf − φ.", "Below threshold, no emission.", "Intensity changes the number of photoelectrons.", "λ = h/p.", "h = 6.626 × 10⁻³⁴ J s."],
        practice: [{ id: "c12-photo-p1", question: "The work function is 2 eV and the photon energy is 1.5 eV. Are electrons emitted?", hint: "Compare hf and φ. You do not need a calculator.", answer: "No. The photon energy is below the work function." }],
        quiz: [
          { id: "c12-photo-q1", question: "Below the threshold frequency…", choices: ["no photoelectrons are emitted", "emission starts if you wait", "K_max is large", "the work function becomes zero"], answerIndex: 0, explanation: "hf must be at least φ." },
          { id: "c12-photo-q2", question: "de Broglie wavelength uses…", choices: ["h/p", "F/A", "mgh", "IR"], answerIndex: 0, explanation: "λ = h/p." },
        ],
      },
      {
        id: "c12-nucleus",
        title: "Nuclei",
        aliases: ["half life", "half-life", "radioactivity", "radioactive decay", "mass defect"],
        idea: "After one half-life, half of the radioactive nuclei that can decay are still left. The checker uses N = N₀(1/2)^(t/T). It does not guess a decay that was not measured.",
        younger: "If the half-life is 2 hours, one quarter of the original nuclei remain after 4 hours. The checker uses N = N₀(1/2)^(t/T). It does not guess a decay that was not measured.",
        senior: "Half-life is statistical. It does not say which nucleus decays next. Mass defect is the difference between the mass of a nucleus and the masses of its separate nucleons. The binding energy is that difference times c².",
        example: "8000 nuclei with a half-life of 3 days leave 1000 nuclei after 9 days, which is three half-lives.",
        formulaIds: ["half-life", "mass-defect"],
        sketch: "nucleus",
        mistake: { wrong: "After two half-lives, nothing remains.", right: "One quarter of the original number remains." },
        check: { question: "The half-life is 5 days. What fraction remains after 15 days?", answer: "1/8, because 15 days is three half-lives." },
        keyPoints: ["N = N₀ / 2ⁿ after n half-lives.", "Half-life is statistical.", "Mass defect is tied to binding energy by E = Δm c².", "The checker will not invent a half-life."],
        worked: {
          prompt: "8000 nuclei have a half-life of 3 days. How many remain after 9 days?",
          formulaId: "half-life",
          known: { N0: { value: 8000, unit: "1" }, T: { value: 3, unit: "day" }, t: { value: 9, unit: "day" } },
          find: "N",
          after: "9 days is three half-lives, so 8000/8 = 1000 remain.",
        },
        practice: [{ id: "c12-nucleus-p1", question: "What fraction of a sample remains after two half-lives?", hint: "Halve it twice.", answer: "One quarter." }],
        quiz: [
          { id: "c12-nucleus-q1", question: "After one half-life, the remaining fraction is…", choices: ["1/2", "0", "1/4", "2"], answerIndex: 0, explanation: "Half of the nuclei remain." },
          { id: "c12-nucleus-q2", question: "Mass defect is the difference between…", choices: ["the mass of a nucleus and the masses of its separate nucleons", "the half-life and the period", "voltage and current", "the work function and a photon"], answerIndex: 0, explanation: "That missing mass corresponds to the binding energy." },
        ],
      },
    ],
  },
];
