import type { PracticeItem } from "@/content/types";

export type ExtraSum = PracticeItem & { topic: string };

const sums: Record<string, ExtraSum[]> = {
  "c6-motion": [
    {
      id: "c6-motion-x1",
      topic: "Distance and time",
      question: "A child walks 600 m in 30 s. Find the speed.",
      hint: "Speed = distance ÷ time.",
      answer: "20 m/s.",
      worked: { formulaId: "speed", known: { s: { value: 600, unit: "m" }, t: { value: 30, unit: "s" } }, find: "v" },
    },
    {
      id: "c6-motion-x2",
      topic: "Distance and time",
      question: "A toy car moves at 5 m/s for 12 s. How far does it go?",
      hint: "Distance = speed × time.",
      answer: "60 m.",
      worked: { formulaId: "speed", known: { v: { value: 5, unit: "m/s" }, t: { value: 12, unit: "s" } }, find: "s" },
    },
  ],
  "c7-speed": [
    {
      id: "c7-speed-x1",
      topic: "Speed",
      question: "A bus covers 240 km in 4 hours. Find its speed.",
      hint: "Divide distance by time.",
      answer: "60 km/h.",
      worked: { formulaId: "speed", known: { s: { value: 240, unit: "km" }, t: { value: 4, unit: "h" } }, find: "v" },
    },
    {
      id: "c7-speed-x2",
      topic: "Speed",
      question: "A cyclist rides at 18 m/s for 10 s. Find the distance.",
      hint: "Multiply speed by time.",
      answer: "180 m.",
      worked: { formulaId: "speed", known: { v: { value: 18, unit: "m/s" }, t: { value: 10, unit: "s" } }, find: "s" },
    },
  ],
  "c8-pressure": [
    {
      id: "c8-pressure-x1",
      topic: "Pressure",
      question: "A 40 N force acts on an area of 0.2 m². Find the pressure.",
      hint: "Pressure = force ÷ area.",
      answer: "200 Pa.",
      worked: { formulaId: "pressure", known: { F: { value: 40, unit: "N" }, A: { value: 0.2, unit: "m²" } }, find: "P" },
    },
  ],
  "c8-friction-sound": [
    {
      id: "c8-sound-x1",
      topic: "Sound",
      question: "A sound wave has frequency 500 Hz and wavelength 0.68 m. Find the speed.",
      hint: "Speed = frequency × wavelength.",
      answer: "340 m/s.",
      worked: { formulaId: "wave-speed", known: { f: { value: 500, unit: "Hz" }, lambda: { value: 0.68, unit: "m" } }, find: "v" },
    },
  ],
  "c9-motion": [
    {
      id: "c9-motion-x1",
      topic: "Equations of motion",
      question: "A body starts from rest and accelerates at 4 m/s² for 3 s. How far does it travel?",
      hint: "Use s = ut + ½at² with u = 0.",
      answer: "18 m.",
      worked: { formulaId: "s-uat", known: { u: { value: 0, unit: "m/s" }, a: { value: 4, unit: "m/s²" }, t: { value: 3, unit: "s" } }, find: "s" },
    },
    {
      id: "c9-motion-x2",
      topic: "Velocity",
      question: "A runner covers 180 m due east in 20 s. Find the velocity if east is the positive direction.",
      hint: "Velocity = displacement ÷ time, and keep the direction.",
      answer: "9 m/s east.",
      worked: { formulaId: "velocity", known: { s: { value: 180, unit: "m" }, t: { value: 20, unit: "s" } }, find: "v" },
    },
    {
      id: "c9-motion-x3",
      topic: "Acceleration",
      question: "A bike speeds up from 5 m/s to 17 m/s in 4 s. Find the acceleration.",
      hint: "a = (v − u) / t.",
      answer: "3 m/s².",
      worked: { formulaId: "acceleration", known: { u: { value: 5, unit: "m/s" }, v: { value: 17, unit: "m/s" }, t: { value: 4, unit: "s" } }, find: "a" },
    },
  ],
  "c9-laws": [
    {
      id: "c9-laws-x1",
      topic: "Newton’s second law",
      question: "A 3 kg trolley accelerates at 2 m/s². Find the net force.",
      hint: "F = ma.",
      answer: "6 N.",
      worked: { formulaId: "newton-second", known: { m: { value: 3, unit: "kg" }, a: { value: 2, unit: "m/s²" } }, find: "F" },
    },
    {
      id: "c9-laws-x2",
      topic: "Momentum",
      question: "Find the momentum of a 5 kg cart moving at 4 m/s.",
      hint: "p = mv.",
      answer: "20 kg m/s.",
      worked: { formulaId: "momentum", known: { m: { value: 5, unit: "kg" }, v: { value: 4, unit: "m/s" } }, find: "p" },
    },
  ],
  "c9-gravity": [
    {
      id: "c9-gravity-x1",
      topic: "Weight",
      question: "A 4 kg bag is weighed where g = 9.8 m/s². Find its weight.",
      hint: "Weight = mass × g.",
      answer: "39.2 N.",
      worked: { formulaId: "weight", known: { m: { value: 4, unit: "kg" }, g: { value: 9.8, unit: "m/s²" } }, find: "W" },
    },
    {
      id: "c9-gravity-x2",
      topic: "Free fall",
      question: "A ball is dropped from rest. Take g = 10 m/s² downward. Find its speed after 3 s.",
      hint: "v = u + gt with u = 0.",
      answer: "30 m/s downward.",
      worked: { formulaId: "v-uat", known: { u: { value: 0, unit: "m/s" }, a: { value: 10, unit: "m/s²" }, t: { value: 3, unit: "s" } }, find: "v" },
    },
  ],
  "c9-energy": [
    {
      id: "c9-energy-x1",
      topic: "Kinetic energy",
      question: "A 4 kg stone moves at 5 m/s. Find its kinetic energy.",
      hint: "K = ½mv².",
      answer: "50 J.",
      worked: { formulaId: "kinetic-energy", known: { m: { value: 4, unit: "kg" }, v: { value: 5, unit: "m/s" } }, find: "K" },
    },
    {
      id: "c9-energy-x2",
      topic: "Potential energy",
      question: "A 3 kg book is lifted 2 m. Take g = 10 m/s². Find the gain in potential energy.",
      hint: "U = mgh.",
      answer: "60 J.",
      worked: { formulaId: "potential-energy", known: { m: { value: 3, unit: "kg" }, g: { value: 10, unit: "m/s²" }, h: { value: 2, unit: "m" } }, find: "U" },
    },
  ],
  "c9-sound": [
    {
      id: "c9-sound-x1",
      topic: "Echo",
      question: "Sound travels at 340 m/s. An echo returns in 2 s. How far away is the wall?",
      hint: "The sound goes to the wall and back, so halve the round trip.",
      answer: "340 m.",
      worked: { formulaId: "echo-distance", known: { v: { value: 340, unit: "m/s" }, t: { value: 2, unit: "s" } }, find: "d" },
    },
    {
      id: "c9-sound-x2",
      topic: "Wave speed",
      question: "A wave has frequency 250 Hz and wavelength 1.2 m. Find the speed.",
      hint: "v = fλ.",
      answer: "300 m/s.",
      worked: { formulaId: "wave-speed", known: { f: { value: 250, unit: "Hz" }, lambda: { value: 1.2, unit: "m" } }, find: "v" },
    },
  ],
  "c10-light": [
    {
      id: "c10-light-x1",
      topic: "Power of a lens",
      question: "A convex lens has focal length 0.5 m. Find its power.",
      hint: "P = 1/f when f is in metres.",
      answer: "2 D.",
      worked: { formulaId: "lens-power", known: { f: { value: 0.5, unit: "m" } }, find: "P" },
    },
    {
      id: "c10-light-x2",
      topic: "Power of a lens",
      question: "A lens has power −5 D. Find its focal length in metres.",
      hint: "f = 1/P. A negative power means a concave lens.",
      answer: "−0.2 m.",
      worked: { formulaId: "lens-power", known: { P: { value: -5, unit: "D" } }, find: "f" },
    },
  ],
  "c10-electricity": [
    {
      id: "c10-ohm-x1",
      topic: "Ohm’s law",
      question: "A resistor of 3 ohm is connected to 9 V. Find the current.",
      hint: "I = V / R.",
      answer: "3 A.",
      worked: { formulaId: "ohms-law", known: { V: { value: 9, unit: "V" }, R: { value: 3, unit: "ohm" } }, find: "I" },
    },
    {
      id: "c10-series-x1",
      topic: "Series circuit",
      question: "Resistors of 4 ohm and 6 ohm are in series. Find the equivalent resistance.",
      hint: "Add the resistances.",
      answer: "10 ohm.",
      worked: { formulaId: "series-resistance", known: { R1: { value: 4, unit: "ohm" }, R2: { value: 6, unit: "ohm" } }, find: "R" },
    },
    {
      id: "c10-power-x1",
      topic: "Electric power",
      question: "A lamp works at 12 V and 0.5 A. Find the power.",
      hint: "P = VI.",
      answer: "6 W.",
      worked: { formulaId: "electric-power", known: { V: { value: 12, unit: "V" }, I: { value: 0.5, unit: "A" } }, find: "P" },
    },
  ],
  "c11-mechanics": [
    {
      id: "c11-mech-x1",
      topic: "Force",
      question: "A 6 kg box has a net force of 18 N. Find its acceleration.",
      hint: "a = F / m.",
      answer: "3 m/s².",
      worked: { formulaId: "newton-second", known: { F: { value: 18, unit: "N" }, m: { value: 6, unit: "kg" } }, find: "a" },
    },
    {
      id: "c11-mech-x2",
      topic: "Work",
      question: "A 12 N force moves a box 5 m along the force. Find the work done.",
      hint: "When the force and the move are in the same direction, W = Fs.",
      answer: "60 J.",
      worked: { formulaId: "work", known: { F: { value: 12, unit: "N" }, s: { value: 5, unit: "m" } }, find: "W" },
    },
    {
      id: "c11-mech-x3",
      topic: "Kinetic energy",
      question: "A 2 kg puck slides at 6 m/s. Find its kinetic energy.",
      hint: "K = ½mv².",
      answer: "36 J.",
      worked: { formulaId: "kinetic-energy", known: { m: { value: 2, unit: "kg" }, v: { value: 6, unit: "m/s" } }, find: "K" },
    },
  ],
  "c11-oscillations": [
    {
      id: "c11-osc-x1",
      topic: "Simple pendulum",
      question: "A pendulum has length 1 m. Take g = 9.8 m/s² and π = 3.14. Find the period.",
      hint: "T = 2π√(L/g).",
      answer: "About 2.0 s.",
      worked: { formulaId: "pendulum-period", known: { L: { value: 1, unit: "m" }, g: { value: 9.8, unit: "m/s²" } }, find: "T" },
    },
    {
      id: "c11-osc-x2",
      topic: "Spring",
      question: "A spring has k = 200 N/m and the mass is 0.5 kg. Find the period.",
      hint: "T = 2π√(m/k).",
      answer: "About 0.314 s.",
      worked: { formulaId: "spring-period", known: { m: { value: 0.5, unit: "kg" }, k: { value: 200, unit: "N/m" } }, find: "T" },
    },
  ],
  "c11-heat": [
    {
      id: "c11-heat-x1",
      topic: "Heat",
      question: "Find the heat needed for 2 kg of a material with c = 420 J/kg°C to rise by 10°C.",
      hint: "Q = mcΔT.",
      answer: "8400 J.",
      worked: { formulaId: "heat-capacity", known: { m: { value: 2, unit: "kg" }, c: { value: 420, unit: "J/kg°C" }, dT: { value: 10, unit: "°C" } }, find: "Q" },
    },
    {
      id: "c11-heat-x2",
      topic: "Heat",
      question: "0.5 kg of water, c = 4200 J/kg°C, is warmed by 2°C. Find Q.",
      hint: "Multiply mass, specific heat, and the temperature rise.",
      answer: "4200 J.",
      worked: { formulaId: "heat-capacity", known: { m: { value: 0.5, unit: "kg" }, c: { value: 4200, unit: "J/kg°C" }, dT: { value: 2, unit: "°C" } }, find: "Q" },
    },
  ],
  "c12-electrostatics": [
    {
      id: "c12-coulomb-x1",
      topic: "Coulomb’s law",
      question: "Two charges of 1 μC are 1 m apart in air. Take k = 9 × 10⁹. Find the force.",
      hint: "F = k |q1 q2| / r². 1 μC = 10⁻⁶ C.",
      answer: "9 × 10⁻³ N.",
    },
    {
      id: "c12-field-x1",
      topic: "Electric field",
      question: "A charge of 2 μC is in air. Find the field magnitude 2 m away. Take k = 9 × 10⁹.",
      hint: "E = k |q| / r².",
      answer: "4500 N/C.",
    },
  ],
  "c12-current": [
    {
      id: "c12-ohm-x1",
      topic: "Current",
      question: "A wire has resistance 5 ohm and a potential difference of 10 V. Find the current.",
      hint: "I = V / R.",
      answer: "2 A.",
      worked: { formulaId: "ohms-law", known: { V: { value: 10, unit: "V" }, R: { value: 5, unit: "ohm" } }, find: "I" },
    },
    {
      id: "c12-power-x1",
      topic: "Power",
      question: "A heater draws 2 A from a 220 V supply. Find the power.",
      hint: "P = VI.",
      answer: "440 W.",
      worked: { formulaId: "electric-power", known: { V: { value: 220, unit: "V" }, I: { value: 2, unit: "A" } }, find: "P" },
    },
  ],
  "c12-induction": [
    {
      id: "c12-transformer-x1",
      topic: "Transformer",
      question: "A transformer has 200 turns on the primary and 50 turns on the secondary. The primary voltage is 240 V. Find the secondary voltage, assuming an ideal transformer.",
      hint: "Vs / Vp = Ns / Np.",
      answer: "60 V.",
    },
  ],
  "c12-modern": [
    {
      id: "c12-half-x1",
      topic: "Half-life",
      question: "A sample has mass 16 g and a half-life of 3 hours. What mass remains after 6 hours?",
      hint: "6 hours is two half-lives, so the mass is halved twice.",
      answer: "4 g.",
    },
    {
      id: "c12-half-x2",
      topic: "Half-life",
      question: "After one half-life, 40 g of a sample remains. What was the original mass?",
      hint: "One half-life leaves half of the original mass.",
      answer: "80 g.",
    },
  ],
};

export function extraSums(chapterId: string): ExtraSum[] {
  return sums[chapterId] ?? [];
}
